(() => {
  const image = "/static/images/total-solutions-social-1200x630.png";
  const articles = [
    { slug: "quien-cuida-propiedad-despues-de-la-venta", category: "Brokers / Inmobiliarias", title: "¿Quién cuida la propiedad después de entregar las llaves?", description: "La entrega no termina la responsabilidad operativa: una red confiable mantiene la propiedad lista para su siguiente etapa.", author: "Total Solutions Cancún", date: "2026-09-11", minutes: 5, hero_image: "/assets/blog/images/quien-cuida-propiedad-despues-de-la-venta.jpg", image_width: 1200, image_height: 900, image_alt: "Broker entrega las llaves de una propiedad mientras un técnico da continuidad al mantenimiento", sections: [["La operación continúa después de la venta", "Cuando una propiedad cambia de manos, aparecen tareas que no siempre caben en la agenda del propietario: revisiones, reparaciones, instalaciones y evidencias."], ["Un respaldo para brokers e inmobiliarias", "La coordinación profesional permite registrar la solicitud, entender el alcance, asignar el perfil adecuado y documentar el resultado."], ["Una experiencia más confiable para el propietario", "La propiedad recibe atención organizada y el cliente conserva visibilidad sobre el proceso."]] },
    { slug: "cuidar-propiedad-cancun-desde-el-extranjero", category: "Propietarios / Inversionistas", title: "Cómo cuidar una propiedad en Cancún cuando vives en otra ciudad o país", description: "Mantenimiento coordinado, evidencias y seguimiento para propietarios que necesitan operar a distancia.", author: "Total Solutions Cancún", date: "2026-09-11", minutes: 6, hero_image: "/assets/blog/images/cuidar-propiedad-cancun-desde-el-extranjero.jpg", image_width: 1200, image_height: 900, image_alt: "Propietario supervisa a distancia el mantenimiento de una propiedad en Cancún", sections: [["La distancia aumenta el costo de la incertidumbre", "Cuando el propietario no está en Cancún, un problema pequeño puede crecer antes de ser visto. La prioridad es contar con información clara y evidencia."], ["De la solicitud a la conclusión", "Un flujo ordenado conecta solicitud, diagnóstico, supervisión, técnico, evidencias y conclusión."], ["Una red local con visibilidad", "El respaldo local facilita decidir a tiempo y mantener el control sin estar físicamente en el inmueble."]] },
    { slug: "mantenimiento-preventivo-airbnb-cancun", category: "Airbnb / Property Managers", title: "Mantenimiento preventivo para Airbnb y renta vacacional en Cancún", description: "Una agenda preventiva protege la experiencia del huésped y reduce interrupciones operativas.", author: "Total Solutions Cancún", date: "2026-09-11", minutes: 5, hero_image: "/assets/blog/images/mantenimiento-preventivo-airbnb-cancun.jpg", image_width: 1200, image_height: 900, image_alt: "Anfitrión supervisa el mantenimiento preventivo de una propiedad de renta vacacional en Cancún mientras un técnico realiza una inspección", sections: [["Prevenir es proteger la operación", "En una renta vacacional, una falla afecta al huésped, la disponibilidad y la reputación del inmueble."], ["Qué conviene observar", "Instalaciones, equipos, humedad, filtraciones y accesorios merecen una revisión adaptada al tipo de propiedad."], ["Evidencia para decidir mejor", "Fotos, diagnóstico y conclusión permiten comparar necesidades y priorizar intervenciones."]] }
  ];
  const esc = value => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const articleUrl = article => `/blog/${article.slug}`;
  const nav = () => `<nav class="public-nav" aria-label="Public navigation"><a class="public-brand" href="/"><img src="/assets/assets/total-solutions-logo.svg" alt="Total Solutions Cancún" width="178" height="54"></a><button class="public-menu" type="button" aria-expanded="false" aria-controls="blogPublicLinks" aria-label="Abrir menú">☰</button><div class="public-links" id="blogPublicLinks"><a href="/quienes-somos">Quiénes somos</a><a href="/como-funciona">Cómo funciona</a><a href="/blog" aria-current="page">Blog</a><a href="/preguntas-frecuentes">Preguntas frecuentes</a><a class="public-cta" href="/solicitar-servico">Solicitar servicio</a><div class="public-language" aria-label="Language"><a href="?lang=es" aria-label="Español">ES</a><a href="?lang=en" aria-label="English">EN</a><a href="?lang=pt-BR" aria-label="Português">PT</a></div></div></nav>`;
  const bindNav = () => { const menu = document.querySelector(".public-menu"); const links = document.getElementById("blogPublicLinks"); if (!menu || !links) return; menu.addEventListener("click", () => { const open = links.classList.toggle("is-open"); menu.setAttribute("aria-expanded", String(open)); menu.textContent = open ? "×" : "☰"; menu.setAttribute("aria-label", open ? "Cerrar menú" : "Abrir menú"); }); };
  const footer = () => `<footer class="public-footer"><span>Mantenimiento profesional y seguimiento operativo en Cancún.</span><span><a href="https://wa.me/529984078199" target="_blank" rel="noopener">Hablar por WhatsApp</a> · <a href="https://instagram.com/totalsolutionscancun" target="_blank" rel="noopener">Instagram</a></span></footer>`;
  const setMeta = (name, content) => document.querySelector(`meta[name="${name}"]`)?.setAttribute("content", content);
  const schema = data => { document.querySelector("script[data-blog-schema]")?.remove(); const script = document.createElement("script"); script.type = "application/ld+json"; script.dataset.blogSchema = "true"; script.textContent = JSON.stringify(data); document.head.appendChild(script); };
  const card = article => { const articleImage = article.hero_image || image; const alt = article.image_alt || `Total Solutions Cancún - ${article.category}`; const imageClass = article.hero_image ? "blog-card-image-editorial" : ""; return `<article class="blog-card"><img class="${imageClass}" src="${articleImage}" alt="${esc(alt)}" width="${article.image_width || 1200}" height="${article.image_height || 630}" loading="lazy"><div class="blog-card-body"><p class="blog-category">${esc(article.category)}</p><h3>${esc(article.title)}</h3><p>${esc(article.description)}</p><p class="blog-meta">${esc(article.author)} · ${article.minutes} min · ${article.date}</p><a class="blog-link" href="${articleUrl(article)}">Leer artículo <span aria-hidden="true">→</span></a></div></article>`; };
  const shell = (title, text, content) => `${nav()}<header class="blog-hero"><div class="blog-hero-inner"><p class="public-kicker">Total Solutions Cancún</p><h1>${esc(title)}</h1><p>${esc(text)}</p></div></header><main class="blog-content">${content}</main>${footer()}`;
  const renderIndex = () => { const title = "Blog"; const description = "Ideas prácticas sobre mantenimiento profesional para propiedades, hoteles, Airbnb e inversiones en Cancún."; const url = "https://totalsolutionscancun.com/blog"; document.title = `${title} | Total Solutions Cancún`; setMeta("description", description); schema({"@context":"https://schema.org","@type":"CollectionPage",name:title,description,url,mainEntity:articles.map(a => ({"@type":"Article",headline:a.title,url:`https://totalsolutionscancun.com${articleUrl(a)}`,author:{"@type":"Organization",name:a.author},datePublished:a.date}))}); const filters = ["Todos", ...new Set(articles.map(a => a.category))]; document.body.innerHTML = shell(title, "Ideas para cuidar mejor una propiedad y coordinar mantenimiento con más claridad.", `<div class="blog-toolbar"><div><h2>Contenido por contexto</h2></div><p>Perspectivas prácticas para brokers, propietarios, inversionistas, Airbnb y administradores.</p></div><div class="blog-filters" role="group" aria-label="Filtrar artículos">${filters.map((filter, i) => `<button type="button" class="blog-filter" data-filter="${esc(filter)}" aria-pressed="${i === 0}">${esc(filter)}</button>`).join("")}</div><div class="blog-grid">${articles.map(card).join("")}</div>`); bindNav(); document.querySelectorAll(".blog-filter").forEach(button => button.addEventListener("click", () => { const filter = button.dataset.filter; document.querySelectorAll(".blog-filter").forEach(item => item.setAttribute("aria-pressed", String(item === button))); document.querySelectorAll(".blog-card").forEach((item, i) => { item.hidden = filter !== "Todos" && articles[i].category !== filter; }); })); };
  const renderPost = article => { const url = `https://totalsolutionscancun.com${articleUrl(article)}`; const articleImage = article.hero_image || image; const alt = article.image_alt || article.title; document.title = `${article.title} | Total Solutions Cancún`; setMeta("description", article.description); document.querySelector('link[rel="canonical"]').href = url; document.querySelector('meta[property="og:title"]').content = article.title; document.querySelector('meta[property="og:description"]').content = article.description; document.querySelector('meta[property="og:url"]').content = url; document.querySelector('meta[property="og:image"]').content = `https://totalsolutionscancun.com${articleImage}`; schema({"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,image:[`https://totalsolutionscancun.com${articleImage}`],author:{"@type":"Organization",name:article.author},publisher:{"@type":"Organization",name:"Total Solutions Cancún",logo:{"@type":"ImageObject",url:"https://totalsolutionscancun.com/assets/assets/total-solutions-logo.svg"}},datePublished:article.date,dateModified:article.date,mainEntityOfPage:{"@type":"WebPage","@id":url}}); const body = `<a class="blog-back" href="/blog">← Volver al blog</a><article class="blog-article"><p class="blog-category">${esc(article.category)}</p><h1>${esc(article.title)}</h1><p class="blog-dek">${esc(article.description)}</p><p class="blog-meta">${esc(article.author)} · ${article.minutes} min de lectura · ${article.date}</p><figure><img src="${articleImage}" alt="${esc(alt)}" width="${article.image_width || 1200}" height="${article.image_height || 630}" loading="eager"><figcaption>Total Solutions Cancún · mantenimiento profesional en Cancún.</figcaption></figure>${article.sections.map(([heading, text]) => `<section><h2>${esc(heading)}</h2><p>${esc(text)}</p></section>`).join("")}<div class="public-callout"><div><h2>Solicitar un servicio</h2><p>Coordinamos la solicitud, la visita y el seguimiento.</p></div><a href="/solicitar-servico">Solicitar servicio</a></div></article><section class="blog-related"><h2>También puede interesarte</h2><div class="blog-grid">${articles.filter(item => item.slug !== article.slug).map(card).join("")}</div></section>`; document.body.innerHTML = shell(article.title, article.description, body); bindNav(); };
  const slug = decodeURIComponent(location.pathname.replace(/^\/blog\/?/, "").replace(/\/$/, ""));
  const article = articles.find(item => item.slug === slug);
  if (document.body.dataset.blogPage === "post" && article) renderPost(article); else if (document.body.dataset.blogPage === "post") { document.title = "Artículo no encontrado | Total Solutions Cancún"; document.body.innerHTML = shell("Artículo no encontrado", "El contenido solicitado no está disponible.", `<p>Consulta los artículos disponibles en el <a class="blog-link" href="/blog">Blog</a>.</p>`); bindNav(); } else renderIndex();
})();
