(() => {
  const languageKey = "totalsolutions_public_language";
  const image = "/static/images/total-solutions-social-1200x630.png";
  const languages = ["es", "en", "pt-BR"];
  const copy = {
    es: {
      navAbout: "Quiénes somos", navHow: "Cómo funciona", navFaq: "Preguntas frecuentes", navRequest: "Solicitar servicio", menu: "Abrir menú", close: "Cerrar menú", back: "Volver al blog", read: "Leer artículo", readTime: "min de lectura", related: "También puede interesarte", all: "Todos", context: "Contenido por contexto", intro: "Ideas para cuidar mejor una propiedad y coordinar mantenimiento con más claridad.", toolbar: "Perspectivas prácticas para brokers, propietarios, inversionistas, Airbnb y administradores.", footer: "Mantenimiento profesional y seguimiento operativo en Cancún.", whatsapp: "Hablar por WhatsApp", request: "Solicitar un servicio", requestText: "Coordinamos la solicitud, la visita y el seguimiento.", notFound: "Artículo no encontrado", notFoundText: "El contenido solicitado no está disponible.", notFoundHelp: "Consulta los artículos disponibles en el Blog.", categories: { brokers: "Brokers / Inmobiliarias", owners: "Propietarios / Inversionistas", airbnb: "Airbnb / Property Managers" }, labels: { brokers: "Broker entrega las llaves de una propiedad mientras un técnico da continuidad al mantenimiento", owners: "Propietario supervisa a distancia el mantenimiento de una propiedad en Cancún", airbnb: "Anfitrión supervisa el mantenimiento preventivo de una propiedad de renta vacacional en Cancún mientras un técnico realiza una inspección" }, articles: [
        { title: "¿Quién cuida la propiedad después de entregar las llaves?", description: "La entrega no termina la responsabilidad operativa: una red confiable mantiene la propiedad lista para su siguiente etapa.", sections: [["La operación continúa después de la venta", "Cuando una propiedad cambia de manos, aparecen tareas que no siempre caben en la agenda del propietario: revisiones, reparaciones, instalaciones y evidencias."], ["Un respaldo para brokers e inmobiliarias", "La coordinación profesional permite registrar la solicitud, entender el alcance, asignar el perfil adecuado y documentar el resultado."], ["Una experiencia más confiable para el propietario", "La propiedad recibe atención organizada y el cliente conserva visibilidad sobre el proceso."]] },
        { title: "Cómo cuidar una propiedad en Cancún cuando vives en otra ciudad o país", description: "Mantenimiento coordinado, evidencias y seguimiento para propietarios que necesitan operar a distancia.", sections: [["La distancia aumenta el costo de la incertidumbre", "Cuando el propietario no está en Cancún, un problema pequeño puede crecer antes de ser visto. La prioridad es contar con información clara y evidencia."], ["De la solicitud a la conclusión", "Un flujo ordenado conecta solicitud, diagnóstico, supervisión, técnico, evidencias y conclusión."], ["Una red local con visibilidad", "El respaldo local facilita decidir a tiempo y mantener el control sin estar físicamente en el inmueble."]] },
        { title: "Mantenimiento preventivo para Airbnb y renta vacacional en Cancún", description: "Una agenda preventiva protege la experiencia del huésped y reduce interrupciones operativas.", sections: [["Prevenir es proteger la operación", "En una renta vacacional, una falla afecta al huésped, la disponibilidad y la reputación del inmueble."], ["Qué conviene observar", "Instalaciones, equipos, humedad, filtraciones y accesorios merecen una revisión adaptada al tipo de propiedad."], ["Evidencia para decidir mejor", "Fotos, diagnóstico y conclusión permiten comparar necesidades y priorizar intervenciones."]] }
      ]
    },
    en: {
      navAbout: "About us", navHow: "How it works", navFaq: "FAQ", navRequest: "Request service", menu: "Open menu", close: "Close menu", back: "Back to blog", read: "Read article", readTime: "min read", related: "You may also be interested", all: "All", context: "Content by context", intro: "Practical ideas for caring for a property and coordinating maintenance with greater clarity.", toolbar: "Practical perspectives for brokers, property owners, investors, Airbnb hosts and managers.", footer: "Professional maintenance and operational tracking in Cancún.", whatsapp: "Chat on WhatsApp", request: "Request a service", requestText: "We coordinate the request, visit and follow-up.", notFound: "Article not found", notFoundText: "The requested content is not available.", notFoundHelp: "Browse the available articles in the Blog.", categories: { brokers: "Brokers / Real Estate Agencies", owners: "Property Owners / Investors", airbnb: "Airbnb / Property Managers" }, labels: { brokers: "Broker hands over property keys while a technician continues the maintenance care", owners: "Property owner remotely oversees the maintenance of a property in Cancún", airbnb: "Host oversees preventive maintenance at a vacation rental in Cancún while a technician performs an inspection" }, articles: [
        { title: "Who takes care of the property after the keys are handed over?", description: "Handover does not end operational responsibility: a trusted network keeps the property ready for its next stage.", sections: [["Operations continue after the sale", "When a property changes hands, tasks arise that do not always fit the owner's schedule: inspections, repairs, installations and evidence."], ["A reliable partner for brokers and real estate agencies", "Professional coordination records the request, clarifies its scope, assigns the right profile and documents the outcome."], ["A more reliable experience for the owner", "The property receives organized attention while the client retains visibility throughout the process."]] },
        { title: "How to take care of a property in Cancún when you live in another city or country", description: "Coordinated maintenance, evidence and follow-up for owners who need to operate remotely.", sections: [["Distance increases the cost of uncertainty", "When an owner is not in Cancún, a small issue can grow before it is seen. Clear information and evidence are the priority."], ["From request to conclusion", "An organized flow connects the request, diagnosis, supervision, technician, evidence and conclusion."], ["A local network with visibility", "Local support helps owners make timely decisions and stay in control without being physically at the property."]] },
        { title: "Preventive maintenance for Airbnb and vacation rentals in Cancún", description: "A preventive schedule protects the guest experience and reduces operational interruptions.", sections: [["Prevention protects the operation", "In a vacation rental, a failure affects the guest, availability and the property's reputation."], ["What deserves attention", "Installations, equipment, humidity, leaks and fixtures deserve a review adapted to the property type."], ["Evidence for better decisions", "Photos, diagnosis and conclusion make it easier to compare needs and prioritize interventions."]] }
      ]
    },
    "pt-BR": {
      navAbout: "Quem somos", navHow: "Como funciona", navFaq: "Perguntas frequentes", navRequest: "Solicitar serviço", menu: "Abrir menu", close: "Fechar menu", back: "Voltar ao blog", read: "Ler artigo", readTime: "min de leitura", related: "Você também pode se interessar", all: "Todos", context: "Conteúdo por contexto", intro: "Ideias práticas para cuidar melhor de um imóvel e coordenar a manutenção com mais clareza.", toolbar: "Perspectivas práticas para corretores, proprietários, investidores, Airbnb e gestores.", footer: "Manutenção profissional e acompanhamento operacional em Cancún.", whatsapp: "Falar pelo WhatsApp", request: "Solicitar um serviço", requestText: "Coordenamos a solicitação, a visita e o acompanhamento.", notFound: "Artigo não encontrado", notFoundText: "O conteúdo solicitado não está disponível.", notFoundHelp: "Consulte os artigos disponíveis no Blog.", categories: { brokers: "Corretores / Imobiliárias", owners: "Proprietários / Investidores", airbnb: "Airbnb / Gestores de propriedades" }, labels: { brokers: "Corretor entrega as chaves de um imóvel enquanto um técnico dá continuidade à manutenção", owners: "Proprietário acompanha remotamente a manutenção de um imóvel em Cancún", airbnb: "Anfitrião acompanha a manutenção preventiva de um imóvel de temporada em Cancún enquanto um técnico realiza uma inspeção" }, articles: [
        { title: "Quem cuida do imóvel depois da entrega das chaves?", description: "A entrega não encerra a responsabilidade operacional: uma rede confiável mantém o imóvel pronto para a próxima etapa.", sections: [["A operação continua depois da venda", "Quando um imóvel muda de mãos, surgem tarefas que nem sempre cabem na agenda do proprietário: revisões, reparos, instalações e evidências."], ["Um apoio para corretores e imobiliárias", "A coordenação profissional registra a solicitação, entende o escopo, atribui o perfil adequado e documenta o resultado."], ["Uma experiência mais confiável para o proprietário", "O imóvel recebe atendimento organizado e o cliente mantém visibilidade sobre o processo."]] },
        { title: "Como cuidar de um imóvel em Cancún morando em outra cidade ou país", description: "Manutenção coordenada, evidências e acompanhamento para proprietários que precisam operar à distância.", sections: [["A distância aumenta o custo da incerteza", "Quando o proprietário não está em Cancún, um problema pequeno pode crescer antes de ser percebido. Informação clara e evidências são a prioridade."], ["Da solicitação à conclusão", "Um fluxo organizado conecta solicitação, diagnóstico, supervisão, técnico, evidências e conclusão."], ["Uma rede local com visibilidade", "O apoio local facilita decisões no momento certo e mantém o controle sem estar fisicamente no imóvel."]] },
        { title: "Manutenção preventiva para Airbnb e aluguel por temporada em Cancún", description: "Uma agenda preventiva protege a experiência do hóspede e reduz interrupções operacionais.", sections: [["Prevenir é proteger a operação", "Em uma locação por temporada, uma falha afeta o hóspede, a disponibilidade e a reputação do imóvel."], ["O que merece atenção", "Instalações, equipamentos, umidade, vazamentos e acessórios merecem uma revisão adaptada ao tipo de imóvel."], ["Evidências para decidir melhor", "Fotos, diagnóstico e conclusão ajudam a comparar necessidades e priorizar intervenções."]] }
      ]
    }
  };
  const meta = [
    { slug: "quien-cuida-propiedad-despues-de-la-venta", category: "brokers", minutes: 3, date: "2026-09-11", hero_image: "/assets/blog/images/quien-cuida-propiedad-despues-de-la-venta.jpg", width: 1200, height: 900 },
    { slug: "cuidar-propiedad-cancun-desde-el-extranjero", category: "owners", minutes: 3, date: "2026-09-11", hero_image: "/assets/blog/images/cuidar-propiedad-cancun-desde-el-extranjero.jpg", width: 1200, height: 900 },
    { slug: "mantenimiento-preventivo-airbnb-cancun", category: "airbnb", minutes: 3, date: "2026-09-11", hero_image: "/assets/blog/images/mantenimiento-preventivo-airbnb-cancun.jpg", width: 1200, height: 900 },
    { slug: "como-inmobiliaria-mejorar-servicio-posventa", category: "inmobiliarias", minutes: 5, date: "2026-09-12", hero_image: "/assets/blog/images/como-inmobiliaria-mejorar-servicio-posventa.jpg", width: 1200, height: 900 },
    { slug: "despues-comprar-propiedad-inversion-cancun", category: "investment", minutes: 5, date: "2026-09-12", hero_image: "/assets/blog/images/despues-comprar-propiedad-inversion-cancun.jpg", width: 1200, height: 900 },
    { slug: "senales-aire-acondicionado-necesita-mantenimiento", category: "airconditioning", minutes: 4, date: "2026-09-12", hero_image: "/assets/blog/images/senales-aire-acondicionado-necesita-mantenimiento.jpg", width: 1200, height: 900 }
  ];
  const esc = value => String(value).replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
  const normalizeLanguage = value => String(value || "").toLowerCase().startsWith("pt") ? "pt-BR" : String(value || "").toLowerCase().startsWith("en") ? "en" : "es";
  let lang = normalizeLanguage(new URLSearchParams(location.search).get("lang") || localStorage.getItem(languageKey) || navigator.language);
  const currentCopy = () => copy[lang];
  const articleUrl = article => `/blog/${article.slug}`;
  const nav = () => { const c = currentCopy(); return `<nav class="public-nav" aria-label="Public navigation"><a class="public-brand" href="/"><img src="/assets/assets/total-solutions-logo.svg" alt="Total Solutions Cancún" width="178" height="54"></a><button class="public-menu" type="button" aria-expanded="false" aria-controls="blogPublicLinks" aria-label="${esc(c.menu)}">☰</button><div class="public-links" id="blogPublicLinks"><a href="/quienes-somos">${esc(c.navAbout)}</a><a href="/como-funciona">${esc(c.navHow)}</a><a href="/blog" aria-current="page">Blog</a><a href="/preguntas-frecuentes">${esc(c.navFaq)}</a><a class="public-cta" href="/solicitar-servico">${esc(c.navRequest)}</a><div class="public-language" aria-label="Language">${languages.map(item => `<button type="button" data-lang="${item}" aria-pressed="${lang === item}">${item === "pt-BR" ? "PT" : item.toUpperCase()}</button>`).join("")}</div></div></nav>`; };
  const footer = () => { const c = currentCopy(); return `<footer class="public-footer"><span>${esc(c.footer)}</span><span><a href="https://wa.me/529984078199" target="_blank" rel="noopener">${esc(c.whatsapp)}</a> · <a href="https://instagram.com/totalsolutionscancun" target="_blank" rel="noopener">Instagram</a></span></footer>`; };
  const setMeta = (selector, content) => document.querySelector(selector)?.setAttribute("content", content);
  const setSchema = data => { document.querySelector("script[data-blog-schema]")?.remove(); const script = document.createElement("script"); script.type = "application/ld+json"; script.dataset.blogSchema = "true"; script.textContent = JSON.stringify(data); document.head.appendChild(script); };
  const editorial = {
    es: [
      { description: "La venta termina, pero la relación con la propiedad continúa: una operación posventa organizada ayuda a proteger la experiencia del comprador.", sections: [
        { heading: "La escritura cierra una etapa, no la operación", paragraphs: ["Entregar las llaves suele sentirse como el cierre de una venta. Para el comprador, sin embargo, es el comienzo de una etapa práctica: poner en marcha el aire acondicionado, revisar instalaciones, preparar el inmueble para vivir o dejarlo listo para una renta vacacional.", "En Cancún, muchos propietarios viven en otro estado o país. Cuando aparece una fuga pequeña, una cerradura que necesita ajuste o una pared que requiere pintura, la distancia vuelve más difícil saber a quién llamar y cómo confirmar que el trabajo quedó terminado."] },
        { heading: "El servicio posventa no termina con la escritura", paragraphs: ["Un broker o una inmobiliaria no tiene que convertirse en una empresa de mantenimiento para seguir acompañando a su cliente. Puede bastar con contar con una ruta clara para orientar solicitudes, explicar el siguiente paso y conectar al propietario con apoyo operativo local cuando corresponda.", "Acompañar no significa prometer que todos los problemas desaparecerán. Significa ayudar a que el cliente no quede solo después de la compra y que cada incidencia tenga un registro, un responsable y una conclusión verificable."] },
        { heading: "Problemas que aparecen después de la entrega", paragraphs: ["Los primeros pendientes suelen ser concretos: revisar un minisplit, corregir una fuga, comprobar una bomba o cisterna, verificar una conexión eléctrica, cambiar una cerradura o atender pequeños acabados antes de amueblar. Ninguno es necesariamente una emergencia, pero ignorarlos puede complicar la preparación de la propiedad.", "También existen tareas previas a una renta: comprobar equipos, documentar el estado inicial, revisar accesos y separar lo urgente de lo programable. Un diagnóstico temprano evita decisiones basadas únicamente en mensajes incompletos."] },
        { heading: "Una oportunidad para fortalecer la relación", paragraphs: ["Una referencia operativa responsable permite que la conversación con el comprador continúe de forma útil. El cliente recibe una alternativa concreta, mientras el broker conserva su papel de aliado de confianza sin asumir la ejecución técnica.", "La confianza se construye con claridad: explicar qué puede coordinarse, qué necesita aprobación, qué evidencias se entregarán y qué condiciones aplican. No hace falta prometer resultados garantizados; hace falta que el proceso sea comprensible."] },
        { heading: "Qué conviene dejar organizado", paragraphs: ["Después de entregar una propiedad, conviene dejar una referencia sencilla para el propietario y para quien administre el inmueble."], checklist: ["Contacto para mantenimiento", "Aire acondicionado, plomería y electricidad revisados", "Accesos, cerraduras y personas autorizadas", "Evidencias del estado inicial", "Plan para propiedad vacía o en renta", "Canal para diagnóstico y cotización"] },
        { heading: "Un aliado operativo después de la entrega", paragraphs: ["Total Solutions Cancún puede ayudar a centralizar la solicitud, coordinar una visita, organizar la supervisión, documentar evidencias y comunicar la conclusión cuando el servicio corresponde a su alcance y disponibilidad. El flujo puede conectar solicitud, diagnóstico, coordinación, técnico, seguimiento, evidencias y garantía cuando corresponda.", "La propuesta no es competir por la relación con el comprador. Es ofrecer una opción local que facilite el siguiente paso y mantenga la comunicación ordenada. Si quieres conocer cómo apoyar a tus clientes después de la compra, habla con Total Solutions o solicita un servicio."] }
      ] },
      { description: "Mantenimiento coordinado, evidencias y seguimiento para propietarios que necesitan operar a distancia.", sections: [
        { heading: "El problema no es estar lejos. Es no tener visibilidad.", paragraphs: ["Cancún reúne propiedades de segunda residencia, inversión y renta vacacional cuyos propietarios no viven permanentemente en la ciudad. La distancia no impide cuidar un inmueble, pero vuelve más importante contar con información confiable cuando algo necesita atención.", "Una fotografía aislada o un mensaje corto no siempre basta para decidir. El propietario necesita entender qué se encontró, qué opciones existen, quién visitará el lugar y qué evidencia recibirá al finalizar."] },
        { heading: "Los pequeños problemas también necesitan seguimiento", paragraphs: ["Humedad, fugas visibles, un aire acondicionado detenido, una bomba que requiere revisión, pintura deteriorada o una cerradura que falla pueden parecer asuntos menores. Sin atención oportuna, pueden afectar otras áreas o complicar la llegada de huéspedes y familiares.", "La respuesta no tiene que ser una inspección permanente. Puede ser un procedimiento simple: registrar la necesidad, reunir contexto, coordinar una visita, documentar el diagnóstico y decidir qué se aprueba y qué se programa."] },
        { heading: "De la solicitud a la conclusión", paragraphs: ["Un flujo remoto funciona mejor cuando cada etapa tiene un propósito. Primero se registra el problema y la ubicación; después se revisan las evidencias y se coordina el perfil técnico adecuado. Si hace falta, el diagnóstico define el alcance antes de ejecutar.", "Con la aprobación correspondiente, el servicio se realiza y se documenta. Las evidencias finales permiten confirmar qué se observó y qué se hizo. Cuando aplica una garantía, debe quedar vinculada al alcance real del servicio."], checklist: ["Registrar solicitud, ubicación y contexto", "Compartir fotografías o videos útiles", "Confirmar acceso y persona autorizada", "Recibir diagnóstico y propuesta cuando corresponda", "Aprobar el alcance antes de ejecutar", "Conservar evidencias y conclusión"] },
        { heading: "Checklist antes de dejar el inmueble", paragraphs: ["Si vas a pasar semanas o meses fuera de Cancún, estas comprobaciones pueden reducir incertidumbre y facilitar una atención posterior."], checklist: ["Comprobar aire acondicionado y controles", "Revisar fugas visibles y señales de humedad", "Revisar bombas y cisterna cuando corresponda", "Confirmar accesos, llaves y cerraduras", "Guardar fotografías recientes", "Definir contacto operativo local", "Dejar procedimiento para emergencias", "Conservar historial de mantenimientos"] },
        { heading: "Decidir mejor con información local", paragraphs: ["El valor del apoyo local no está en sustituir al propietario, sino en permitirle decidir con mejores datos sin viajar para cada revisión. Una visita documentada puede aclarar si se trata de un ajuste, una reparación, una intervención programada o una situación que necesita otro especialista.", "No todo pendiente tiene el mismo impacto. Con contexto, evidencias y comunicación clara, el propietario puede cuidar su inversión sin convertir cada mensaje en una urgencia."] },
        { heading: "Cómo puede ayudar Total Solutions", paragraphs: ["Total Solutions Cancún puede ayudar a coordinar solicitud, visita, diagnóstico, técnico, seguimiento y evidencias según el alcance y la disponibilidad del servicio. El propietario mantiene la visibilidad y participa en las decisiones que requieren aprobación.", "No se trata de afirmar que una propiedad queda atendida automáticamente o de ofrecer monitoreo permanente sin contratación. Es un canal organizado para necesidades concretas de mantenimiento o reparación. Solicita un servicio o habla por WhatsApp."] }
      ] },
      { description: "Una agenda preventiva protege la experiencia del huésped y reduce interrupciones operativas.", sections: [
        { heading: "Prevenir es proteger la operación", paragraphs: ["En una renta vacacional, el tiempo entre checkout, limpieza y el siguiente check-in suele ser limitado. Un aire acondicionado con bajo rendimiento, una fuga o una cerradura que no responde pueden convertirse en una incidencia justo cuando el huésped está por llegar.", "El mantenimiento preventivo no elimina todos los problemas ni garantiza cero interrupciones. Crea momentos de revisión para detectar señales, priorizar pendientes y resolver lo que conviene atender antes de que impacte la estancia."] },
        { heading: "Correctivo y preventivo responden a momentos distintos", paragraphs: ["El correctivo comienza cuando alguien reporta una falla: la operación reacciona, entiende el alcance y busca una ventana para resolverla, a menudo bajo mayor presión de tiempo.", "El preventivo parte de una revisión planificada. Permite observar equipos, instalaciones y acabados antes de que exista una queja. No es perfecto, pero organiza la respuesta en un momento más conveniente."] },
        { heading: "Qué conviene detectar antes del huésped", paragraphs: ["La revisión debe adaptarse a la unidad, al uso y a lo que realmente puede comprobarse. Conviene observar climatización, agua, electricidad, accesos, humedad, mobiliario básico y cualquier señal visible que pueda afectar la experiencia.", "Un checklist no sustituye el diagnóstico de un especialista. Ayuda a anfitriones y property managers a no depender solo de la memoria durante el cambio de huéspedes y a registrar evidencias con una base común."], checklist: ["Aire acondicionado, controles y temperatura", "Fugas, presión, drenajes y agua caliente", "Luces, contactos y breakers cuando corresponda", "Cerraduras, llaves y acceso digital cuando exista", "Humedad, daños visibles y acabados", "Evidencias fotográficas de hallazgos"] },
        { heading: "Checklist para una nueva reserva", paragraphs: ["Antes de liberar una unidad, el equipo puede revisar los puntos que suelen generar llamadas durante una estancia. El objetivo es priorizar, no convertir la preparación en una inspección interminable."], checklist: ["CLIMATIZACIÓN: funcionamiento y controles", "AGUA: fugas, presión, drenajes y agua caliente", "ELECTRICIDAD: luces, contactos y señales visibles", "ACCESO: cerraduras, llaves y códigos", "GENERAL: humedad, mobiliario y daños", "EVIDENCIAS: fotos y pendientes registrados"] },
        { heading: "Una operación con varias unidades necesita contexto", paragraphs: ["Cuando una persona administra varias propiedades, una lista informal puede perder información entre mensajes. Registrar la unidad, el hallazgo, la prioridad y la evidencia ayuda a comparar necesidades y decidir qué atender antes de la próxima entrada.", "La coordinación debe respetar el alcance real. Si una revisión revela un problema especializado, puede ser necesario solicitar otra evaluación. Comunicarlo con claridad protege al huésped, al propietario y al equipo."] },
        { heading: "Coordinación y evidencias para decidir mejor", paragraphs: ["Total Solutions Cancún puede ayudar a centralizar solicitudes, coordinar una visita, organizar el diagnóstico, dar seguimiento y documentar la conclusión para una propiedad o una operación con varias unidades, conforme a disponibilidad y alcance.", "No afirmamos una integración oficial con Airbnb ni disponibilidad ilimitada. La propuesta es una ruta clara para necesidades concretas: solicitud, coordinación, técnico, evidencias y conclusión, con garantía cuando corresponda. Solicita mantenimiento o habla por WhatsApp."] }
      ] }
    ],
    en: [],
    "pt-BR": []
  };
  editorial.en = [
    { description: "The sale ends, but the property's relationship continues: organized after-sales support helps protect the buyer's experience.", sections: [
      { heading: "The deed closes a stage, not the operation", paragraphs: ["Handing over the keys often feels like the end of a sale. For the buyer, it is the beginning of practical work: starting the air conditioning, checking installations, preparing the property to live in or getting it ready for a vacation rental.", "In Cancún, many owners live in another state or country. When a small leak, lock adjustment or paint repair appears, distance makes it harder to know whom to call and how to confirm that the work is complete."] },
      { heading: "After-sales service does not end with the deed", paragraphs: ["A broker or real estate agency does not need to become a maintenance company to keep supporting a client. A clear path for directing requests, explaining the next step and connecting the owner with local operational support can be enough when appropriate.", "Support does not mean promising that every problem will disappear. It means helping the client avoid being left alone after the purchase and giving each issue a record, an owner and a verifiable conclusion."] },
      { heading: "Problems that appear after handover", paragraphs: ["Early needs are usually concrete: checking a mini-split, fixing a leak, reviewing a pump or cistern, checking an electrical connection, changing a lock or handling small finishes before furnishing. None is necessarily an emergency, but ignoring it can complicate the property's preparation.", "There are also tasks before a rental: checking equipment, documenting the initial condition, reviewing access and separating urgent work from scheduled work. An early diagnosis avoids decisions based only on incomplete messages."] },
      { heading: "An opportunity to strengthen the relationship", paragraphs: ["A responsible operational reference lets the conversation with the buyer continue in a useful way. The client receives a practical option, while the broker remains a trusted ally without taking on technical execution.", "Trust grows through clarity: explain what can be coordinated, what needs approval, what evidence will be delivered and which conditions apply. There is no need to promise guaranteed outcomes; the process needs to be understandable."] },
      { heading: "What is worth organizing", paragraphs: ["After handing over a property, it helps to leave a simple reference for the owner and whoever manages the property."], checklist: ["Maintenance contact", "Air conditioning, plumbing and electrical review", "Access, locks and authorized people", "Evidence of the initial condition", "Plan for a vacant or rented property", "Channel for diagnosis and estimate"] },
      { heading: "An operational partner after handover", paragraphs: ["Total Solutions Cancún can help centralize a request, coordinate a visit, organize supervision, document evidence and communicate the conclusion when the service fits its scope and availability. The flow can connect request, diagnosis, coordination, technician, follow-up, evidence and warranty when applicable.", "The proposal is not to compete for the buyer relationship. It is to offer a local option that makes the next step easier and keeps communication organized. Talk with Total Solutions or request a service to discuss support after the purchase."] }
    ] },
    { description: "Coordinated maintenance, evidence and follow-up for owners who need to operate remotely.", sections: [
      { heading: "The problem is not being away. It is lacking visibility.", paragraphs: ["Cancún has many second homes, investment properties and vacation rentals whose owners do not live in the city year-round. Distance does not prevent proper care, but it makes reliable information more important whenever something needs attention.", "A single photo or short message is not always enough to decide. An owner needs to understand what was found, what options exist, who will visit and what evidence will be received at the end."] },
      { heading: "Small problems also need follow-up", paragraphs: ["Humidity, visible leaks, a stopped air conditioner, a pump that needs review, worn paint or a failing lock may look minor. Without timely attention, they can affect other areas or complicate the arrival of guests and family.", "The answer does not have to be permanent inspection. It can be a simple procedure: record the need, gather context, coordinate a visit, document the diagnosis and decide what to approve and what to schedule."] },
      { heading: "From request to conclusion", paragraphs: ["A remote workflow works best when each stage has a purpose. First record the issue and location; then review available evidence and coordinate the right technical profile. When needed, diagnosis defines the scope before execution.", "With the appropriate approval, the service is completed and documented. Final evidence lets the owner confirm what was observed and done. When a warranty applies, it should be tied to the real scope of the service."], checklist: ["Record request, location and context", "Share useful photos or videos", "Confirm access and an authorized person", "Receive diagnosis and estimate when applicable", "Approve the scope before execution", "Keep evidence and the conclusion"] },
      { heading: "Checklist before leaving the property", paragraphs: ["If you will be away from Cancún for weeks or months, these checks can reduce uncertainty and make later support easier."], checklist: ["Check the air conditioner and controls", "Look for visible leaks and signs of humidity", "Review pumps and cistern when applicable", "Confirm access, keys and locks", "Save recent photos", "Define a local operational contact", "Leave an incident procedure", "Keep maintenance history"] },
      { heading: "Make better decisions with local information", paragraphs: ["The value of local support is not replacing the owner. It is allowing the owner to decide with better information without traveling for every inspection. A documented visit can clarify whether an issue is an adjustment, repair, scheduled intervention or a matter for another specialist.", "Not every pending item has the same impact. With context, evidence and clear communication, an owner can protect an investment without turning every message into an emergency."] },
      { heading: "How Total Solutions can help", paragraphs: ["Total Solutions Cancún can help coordinate the request, visit, diagnosis, technician, follow-up and evidence according to service scope and availability. The owner keeps visibility and participates in decisions that require approval.", "This is not a claim that a property is automatically monitored or that permanent coverage is included without an agreement. It is an organized channel for concrete maintenance or repair needs. Request a service or chat on WhatsApp."] }
    ] },
    { description: "A preventive schedule protects the guest experience and reduces operational interruptions.", sections: [
      { heading: "Prevention protects the operation", paragraphs: ["In a vacation rental, the window between checkout, cleaning and the next check-in is often limited. An air conditioner with poor performance, a leak or a lock that does not respond can become an incident just as a guest is arriving.", "Preventive maintenance does not eliminate every problem or guarantee zero interruptions. Its role is to create review moments, detect signals, prioritize open items and handle what is best addressed before it affects a stay."] },
      { heading: "Corrective and preventive serve different moments", paragraphs: ["Corrective maintenance starts when someone reports a failure. The operation must react, understand the scope and find a time to solve it, often under greater time pressure.", "Preventive maintenance starts with a planned review. It creates a chance to observe equipment, installations and finishes before a complaint exists. The difference is not that one is perfect; each organizes the response at a different moment."] },
      { heading: "What to detect before the guest arrives", paragraphs: ["The review should match the unit, its use and what can actually be checked. It is useful to observe climate control, water, electricity, access, humidity, basic furniture, pool condition when applicable and any visible signal that could affect the stay.", "A checklist does not replace a specialist diagnosis. It helps hosts and property managers avoid relying only on memory during turnover and gives the team a shared basis for recording evidence."], checklist: ["Air conditioning, controls and temperature", "Leaks, pressure, drains and hot water", "Lights, outlets and breakers when applicable", "Locks, keys and digital access when available", "Humidity, visible damage, finishes and pool when applicable", "Photo evidence of findings"] },
      { heading: "A practical checklist for a new reservation", paragraphs: ["Before releasing a unit, the team can review the points that often generate calls during a stay. The goal is prioritization, not an endless inspection."], checklist: ["CLIMATE: operation and controls", "WATER: leaks, pressure, drains and hot water", "ELECTRICITY: lights, outlets and visible signs", "ACCESS: locks, keys and codes", "GENERAL: humidity, furniture and damage", "EVIDENCE: photos and recorded open items"] },
      { heading: "A multi-unit operation needs context", paragraphs: ["When someone manages several properties, an informal list can lose information across messages. Recording the unit, finding, priority and evidence helps compare needs and decide what must be handled before the next arrival.", "Coordination must also respect the real scope. If a review reveals a specialized issue, another assessment may be needed. Clear communication protects the guest, the owner and the rental team."] },
      { heading: "Coordination and evidence for better decisions", paragraphs: ["Total Solutions Cancún can help centralize maintenance requests, coordinate a visit, organize diagnosis, follow up and document the conclusion for an individual property or a multi-unit operation, according to availability and scope.", "We do not claim an official Airbnb integration or unlimited availability. The proposal is a clear operational path for concrete needs: request, coordination, technician, evidence and conclusion, with warranty when applicable. Request maintenance or chat on WhatsApp."] }
    ] }
  ];
  editorial["pt-BR"] = [
    { description: "A venda termina, mas a relação com o imóvel continua: um pós-venda organizado ajuda a proteger a experiência do comprador.", sections: [
      { heading: "A escritura encerra uma etapa, não a operação", paragraphs: ["A entrega das chaves costuma parecer o fim de uma venda. Para o comprador, porém, é o começo da parte prática: ligar o ar-condicionado, revisar instalações, preparar o imóvel para morar ou deixá-lo pronto para uma locação por temporada.", "Em Cancún, muitos proprietários vivem em outro estado ou país. Quando aparece um pequeno vazamento, um ajuste na fechadura ou uma pintura necessária, a distância torna mais difícil saber quem chamar e como confirmar que o serviço foi concluído."] },
      { heading: "O pós-venda não termina com a escritura", paragraphs: ["Um corretor ou uma imobiliária não precisa se tornar uma empresa de manutenção para continuar apoiando o cliente. Pode bastar ter um caminho claro para orientar solicitações, explicar o próximo passo e conectar o proprietário a um apoio operacional local quando fizer sentido.", "Apoiar não significa prometer que todos os problemas desaparecerão. Significa evitar que o cliente fique sozinho depois da compra e dar a cada ocorrência um registro, um responsável e uma conclusão verificável."] },
      { heading: "Problemas que aparecem depois da entrega", paragraphs: ["As primeiras necessidades costumam ser concretas: verificar um ar-condicionado, corrigir um vazamento, revisar uma bomba ou cisterna, conferir uma conexão elétrica, trocar uma fechadura ou cuidar de pequenos acabamentos antes de mobiliar.", "Também existem tarefas antes de uma locação: testar equipamentos, documentar o estado inicial, revisar acessos e separar o urgente do programável. Um diagnóstico inicial evita decisões baseadas apenas em mensagens incompletas."] },
      { heading: "Uma oportunidade de fortalecer a relação", paragraphs: ["Uma referência operacional responsável permite que a conversa com o comprador continue de forma útil. O cliente recebe uma alternativa prática, enquanto o corretor mantém seu papel de parceiro de confiança sem assumir a execução técnica.", "Confiança é construída com clareza: explicar o que pode ser coordenado, o que precisa de aprovação, quais evidências serão entregues e quais condições se aplicam. Não é preciso prometer resultados garantidos; é preciso tornar o processo compreensível."] },
      { heading: "O que vale deixar organizado", paragraphs: ["Depois de entregar um imóvel, vale deixar uma referência simples para o proprietário e para quem administra a propriedade."], checklist: ["Contato para manutenção", "Revisão de ar-condicionado, hidráulica e elétrica", "Acessos, fechaduras e pessoas autorizadas", "Evidências do estado inicial", "Plano para imóvel vazio ou alugado", "Canal para diagnóstico e orçamento"] },
      { heading: "Um parceiro operacional depois da entrega", paragraphs: ["A Total Solutions Cancún pode ajudar a centralizar uma solicitação, coordenar uma visita, organizar a supervisão, documentar evidências e comunicar a conclusão quando o serviço estiver dentro de seu escopo e disponibilidade. O fluxo pode conectar solicitação, diagnóstico, coordenação, técnico, acompanhamento, evidências e garantia quando aplicável.", "A proposta não é disputar a relação com o comprador. É oferecer uma opção local que facilite o próximo passo e mantenha a comunicação organizada. Fale com a Total Solutions ou solicite um serviço para discutir o apoio após a compra."] }
    ] },
    { description: "Manutenção coordenada, evidências e acompanhamento para proprietários que precisam operar à distância.", sections: [
      { heading: "O problema não é estar longe. É não ter visibilidade.", paragraphs: ["Cancún tem muitos imóveis de segunda residência, investimento e locação por temporada cujos proprietários não vivem na cidade o ano todo. A distância não impede o cuidado, mas torna ainda mais importante contar com informação confiável quando algo precisa de atenção.", "Uma foto isolada ou uma mensagem curta nem sempre basta para decidir. O proprietário precisa entender o que foi encontrado, quais opções existem, quem fará a visita e quais evidências receberá ao final."] },
      { heading: "Pequenos problemas também precisam de acompanhamento", paragraphs: ["Umidade, vazamentos visíveis, ar-condicionado parado, uma bomba que precisa de revisão, pintura desgastada ou uma fechadura com falha podem parecer detalhes. Sem atenção no momento certo, podem afetar outras áreas ou complicar a chegada de hóspedes e familiares.", "A resposta não precisa ser uma inspeção permanente. Pode ser um procedimento simples: registrar a necessidade, reunir o contexto, coordenar uma visita, documentar o diagnóstico e decidir o que aprovar e o que programar."] },
      { heading: "Da solicitação à conclusão", paragraphs: ["Um fluxo remoto funciona melhor quando cada etapa tem um objetivo. Primeiro registra-se o problema e a localização; depois são revisadas as evidências e coordenado o perfil técnico adequado. Quando necessário, o diagnóstico define o escopo antes da execução.", "Com a aprovação correspondente, o serviço é realizado e documentado. As evidências finais permitem confirmar o que foi observado e feito. Quando houver garantia aplicável, ela deve estar ligada ao escopo real do serviço."], checklist: ["Registrar solicitação, localização e contexto", "Compartilhar fotos ou vídeos úteis", "Confirmar acesso e pessoa autorizada", "Receber diagnóstico e orçamento quando aplicável", "Aprovar o escopo antes da execução", "Guardar evidências e conclusão"] },
      { heading: "Checklist antes de deixar o imóvel", paragraphs: ["Se você ficará semanas ou meses longe de Cancún, estas verificações podem reduzir a incerteza e facilitar um atendimento posterior."], checklist: ["Conferir ar-condicionado e controles", "Procurar vazamentos e sinais de umidade", "Revisar bombas e cisterna quando aplicável", "Confirmar acessos, chaves e fechaduras", "Guardar fotos recentes", "Definir um contato operacional local", "Deixar um procedimento para ocorrências", "Manter o histórico de manutenções"] },
      { heading: "Decidir melhor com informação local", paragraphs: ["O valor do apoio local não é substituir o proprietário. É permitir que ele decida com melhores informações sem viajar para cada revisão. Uma visita documentada pode esclarecer se a necessidade é um ajuste, reparo, intervenção programada ou avaliação de outro especialista.", "Nem todo item pendente tem o mesmo impacto. Com contexto, evidências e comunicação clara, o proprietário protege o investimento sem transformar cada mensagem em uma emergência."] },
      { heading: "Como a Total Solutions pode ajudar", paragraphs: ["A Total Solutions Cancún pode ajudar a coordenar solicitação, visita, diagnóstico, técnico, acompanhamento e evidências de acordo com o escopo e a disponibilidade do serviço. O proprietário mantém a visibilidade e participa das decisões que exigem aprovação.", "Isso não significa afirmar que o imóvel é monitorado automaticamente ou que existe cobertura permanente sem contratação. É um canal organizado para necessidades concretas de manutenção ou reparo. Solicite um serviço ou fale pelo WhatsApp."] }
    ] },
    { description: "Uma agenda preventiva protege a experiência do hóspede e reduz interrupções operacionais.", sections: [
      { heading: "Prevenir é proteger a operação", paragraphs: ["Em uma locação por temporada, o intervalo entre checkout, limpeza e o próximo check-in costuma ser curto. Um ar-condicionado com baixo desempenho, um vazamento ou uma fechadura que não responde pode virar uma ocorrência justamente quando o hóspede está chegando.", "A manutenção preventiva não elimina todos os problemas nem garante zero interrupções. Sua função é criar momentos de revisão, detectar sinais, priorizar pendências e cuidar do que é melhor resolver antes de afetar a estadia."] },
      { heading: "Corretiva e preventiva atendem momentos diferentes", paragraphs: ["A manutenção corretiva começa quando alguém informa uma falha. A operação precisa reagir, entender o escopo e encontrar um horário para resolver, muitas vezes sob maior pressão de tempo.", "A preventiva começa com uma revisão planejada. Ela cria uma oportunidade de observar equipamentos, instalações e acabamentos antes de existir uma reclamação. Cada uma organiza a resposta em um momento diferente."] },
      { heading: "O que vale detectar antes do hóspede", paragraphs: ["A revisão deve ser adequada à unidade, ao uso e ao que realmente pode ser verificado. Vale observar climatização, água, eletricidade, acessos, umidade, mobiliário básico, piscina quando aplicável e qualquer sinal visível que possa afetar a experiência.", "Um checklist não substitui o diagnóstico de um especialista. Ele ajuda anfitriões e gestores a registrar evidências durante a troca de hóspedes e a trabalhar com uma base comum."], checklist: ["Ar-condicionado, controles e temperatura", "Vazamentos, pressão, ralos e água quente", "Luzes, tomadas e disjuntores quando aplicável", "Fechaduras, chaves e acesso digital quando existir", "Umidade, danos visíveis, acabamentos e piscina quando aplicável", "Evidências fotográficas dos achados"] },
      { heading: "Checklist para uma nova reserva", paragraphs: ["Antes de liberar uma unidade, a equipe pode revisar os pontos que mais costumam gerar chamadas durante uma estadia. O objetivo é priorizar, não transformar a preparação em uma inspeção interminável."], checklist: ["CLIMATIZAÇÃO: funcionamento e controles", "ÁGUA: vazamentos, pressão, ralos e água quente", "ELÉTRICA: luzes, tomadas e sinais visíveis", "ACESSO: fechaduras, chaves e códigos", "GERAL: umidade, móveis e danos", "EVIDÊNCIAS: fotos e pendências registradas"] },
      { heading: "Uma operação com várias unidades precisa de contexto", paragraphs: ["Quando alguém administra vários imóveis, uma lista informal pode perder informação entre mensagens. Registrar a unidade, o achado, a prioridade e a evidência ajuda a comparar necessidades e decidir o que deve ser atendido antes da próxima chegada.", "A coordenação também precisa respeitar o escopo real. Se uma revisão revelar um problema especializado, pode ser necessária outra avaliação. Comunicar isso com clareza protege o hóspede, o proprietário e a equipe."] },
      { heading: "Coordenação e evidências para decidir melhor", paragraphs: ["A Total Solutions Cancún pode ajudar a centralizar solicitações de manutenção, coordenar uma visita, organizar o diagnóstico, acompanhar e documentar a conclusão de um imóvel ou de uma operação com várias unidades, conforme disponibilidade e escopo.", "Não afirmamos integração oficial com o Airbnb nem disponibilidade ilimitada. A proposta é um caminho operacional claro para necessidades concretas: solicitação, coordenação, técnico, evidências e conclusão, com garantia quando aplicável. Solicite manutenção ou fale pelo WhatsApp."] }
    ] }
  ];
  const cta = {
    es: [
      { ctaTitle: "¿Eres broker o inmobiliaria?", ctaText: "Ofrece a tus clientes una alternativa para acompañar las necesidades de mantenimiento después de la entrega.", ctaLabel: "Hablar con Total Solutions", whatsappMessage: "Hola, soy broker o asesor inmobiliario y me gustaría conocer cómo Total Solutions puede apoyar a mis clientes después de la compra." },
      { ctaTitle: "¿Tienes una propiedad en Cancún y estás lejos?", ctaText: "Coordina una necesidad concreta con información clara, evidencias y seguimiento local.", ctaLabel: "Solicitar un servicio", whatsappMessage: "Hola, tengo una propiedad en Cancún y me gustaría recibir apoyo para coordinar mantenimiento." },
      { ctaTitle: "¿Administras una propiedad de renta vacacional en Cancún?", ctaText: "Organiza el mantenimiento preventivo y correctivo con un flujo claro para tu operación.", ctaLabel: "Solicitar mantenimiento", whatsappMessage: "Hola, administro una propiedad de renta vacacional en Cancún y me gustaría conocer opciones de mantenimiento." }
    ],
    en: [
      { ctaTitle: "Are you a broker or real estate agency?", ctaText: "Offer clients an option for handling maintenance needs after the property handover.", ctaLabel: "Talk with Total Solutions", whatsappMessage: "Hello, I am a broker or real estate adviser and would like to learn how Total Solutions can support my clients after purchase." },
      { ctaTitle: "Do you own a property in Cancún and live elsewhere?", ctaText: "Coordinate a concrete need with clear information, evidence and local follow-up.", ctaLabel: "Request a service", whatsappMessage: "Hello, I have a property in Cancún and would like support coordinating maintenance." },
      { ctaTitle: "Do you manage a vacation rental in Cancún?", ctaText: "Organize preventive and corrective maintenance with a clear operational flow.", ctaLabel: "Request maintenance", whatsappMessage: "Hello, I manage a vacation rental in Cancún and would like to learn about maintenance options." }
    ],
    "pt-BR": [
      { ctaTitle: "Você é corretor ou imobiliária?", ctaText: "Ofereça aos clientes uma alternativa para acompanhar as necessidades de manutenção depois da entrega.", ctaLabel: "Falar com a Total Solutions", whatsappMessage: "Olá, sou corretor ou consultor imobiliário e gostaria de saber como a Total Solutions pode apoiar meus clientes depois da compra." },
      { ctaTitle: "Você tem um imóvel em Cancún e está longe?", ctaText: "Coordene uma necessidade concreta com informação clara, evidências e acompanhamento local.", ctaLabel: "Solicitar um serviço", whatsappMessage: "Olá, tenho um imóvel em Cancún e gostaria de receber apoio para coordenar a manutenção." },
      { ctaTitle: "Você administra um imóvel de temporada em Cancún?", ctaText: "Organize a manutenção preventiva e corretiva com um fluxo operacional claro.", ctaLabel: "Solicitar manutenção", whatsappMessage: "Olá, administro um imóvel de temporada em Cancún e gostaria de conhecer opções de manutenção." }
    ]
  };
  const additionalCopy = {
    es: [
      { title: "Cómo una inmobiliaria puede mejorar su servicio posventa", description: "Una posventa clara ayuda a que el comprador sepa a quién acudir cuando la propiedad necesita atención después de la entrega.", sections: [] },
      { title: "Qué hacer después de comprar una propiedad de inversión en Cancún", description: "Comprar la propiedad es el comienzo: organiza su estado, sus sistemas, sus accesos y la forma de atender incidencias.", sections: [] },
      { title: "5 señales de que tu aire acondicionado necesita mantenimiento", description: "Reconoce señales tempranas en el aire acondicionado antes de que afecten la comodidad, la operación o la llegada de huéspedes.", sections: [] }
    ],
    en: [
      { title: "How a real estate agency can improve its after-sales service", description: "Clear after-sales support helps buyers know where to turn when a property needs attention after handover.", sections: [] },
      { title: "What to do after buying an investment property in Cancún", description: "Buying the property is the beginning: organize its condition, systems, access and incident response.", sections: [] },
      { title: "5 signs your air conditioner needs maintenance", description: "Recognize early air-conditioning signals before they affect comfort, operations or a guest arrival.", sections: [] }
    ],
    "pt-BR": [
      { title: "Como uma imobiliária pode melhorar seu pós-venda", description: "Um pós-venda claro ajuda o comprador a saber a quem recorrer quando o imóvel precisa de atenção depois da entrega.", sections: [] },
      { title: "O que fazer depois de comprar um imóvel de investimento em Cancún", description: "Comprar o imóvel é o começo: organize seu estado, sistemas, acessos e resposta a ocorrências.", sections: [] },
      { title: "5 sinais de que seu ar-condicionado precisa de manutenção", description: "Reconheça sinais iniciais no ar-condicionado antes que afetem o conforto, a operação ou a chegada de hóspedes.", sections: [] }
    ]
  };
  const additionalEditorial = {
    es: [
      { sections: [
        { heading: "La posventa también forma parte de la experiencia", paragraphs: ["La firma y la entrega de llaves son momentos importantes, pero no siempre cierran las preguntas del comprador. Después aparecen ajustes, revisiones y decisiones prácticas que pueden influir en la percepción que el cliente tiene de su compra.", "Una posventa ordenada no promete que nunca habrá problemas. Ofrece una forma clara de registrar una necesidad, entender el siguiente paso y encontrar apoyo local cuando corresponda."] },
        { heading: "Qué ocurre después de la firma y la entrega", paragraphs: ["Los primeros pendientes suelen ser concretos: aire acondicionado, plomería, electricidad, pintura, cerraduras, pequeños ajustes, mantenimiento preventivo o preparación para una renta. Cada propiedad tiene un alcance diferente y no todo debe resolverse de la misma manera.", "Cuando la inmobiliaria ayuda a ordenar la información, el comprador puede separar una incidencia urgente de una mejora programable. Un diagnóstico y evidencias útiles permiten conversar con más claridad antes de decidir."] },
        { heading: "La inmobiliaria no necesita convertirse en una empresa de mantenimiento", paragraphs: ["El papel de una inmobiliaria puede seguir siendo comercial y relacional. No es necesario ejecutar cada reparación ni asumir responsabilidades técnicas para continuar cuidando la experiencia del comprador.", "La idea es mantener un punto de contacto y orientar hacia una operación de apoyo confiable. La frase clave es sencilla: la posventa no consiste en resolver personalmente cada problema, sino en que el cliente sepa a quién acudir."] },
        { heading: "Qué puede organizar una buena estrategia posventa", paragraphs: ["Un procedimiento simple puede definir quién recibe la solicitud, qué información conviene compartir, cómo se coordina una visita y qué ocurre después del diagnóstico. También ayuda explicar qué requiere aprobación y qué evidencias se entregarán.", "Vale la pena dejar organizado un contacto claro, un procedimiento para incidencias, una operación de apoyo, un seguimiento básico, evidencias y un historial cuando corresponda. La consistencia importa más que una promesa amplia."] , checklist: ["Contacto claro para mantenimiento", "Procedimiento para registrar incidencias", "Criterios para solicitar diagnóstico", "Aprobación del alcance antes de ejecutar", "Evidencias y conclusión del servicio", "Historial de necesidades cuando corresponda"] },
        { heading: "Compradores que viven fuera de Cancún", paragraphs: ["Inversionistas, compradores internacionales y propietarios de segunda residencia pueden necesitar apoyo local sin estar disponibles para cada visita. Para ellos, saber qué se encontró y qué se hizo es tan importante como encontrar a la persona adecuada.", "La comunicación debe ser concreta y realista. No se trata de afirmar monitoreo permanente ni resultados garantizados, sino de ofrecer un camino documentado para necesidades específicas."] },
        { heading: "Cómo puede participar Total Solutions", paragraphs: ["Total Solutions puede apoyar el flujo de solicitud, coordinación y supervisión, conectar al técnico adecuado, organizar el diagnóstico, dar seguimiento y documentar evidencias hasta la conclusión, con garantía cuando corresponda.", "La inmobiliaria conserva su relación con el comprador y puede ofrecer una alternativa local sin convertirse en empresa de mantenimiento. Si quieres fortalecer la experiencia posventa de tus clientes, habla con Total Solutions."] }
      ] },
      { sections: [
        { heading: "Comprar la propiedad es el comienzo", paragraphs: ["Después de comprar una propiedad de inversión en Cancún, conviene pasar de la emoción inicial a una organización práctica. El inmueble necesita un punto de partida documentado, responsables claros y una forma de decidir qué atender primero.", "Esto no es una recomendación sobre rentabilidad, impuestos o aspectos legales. Es una guía operativa para conocer mejor el estado físico de la propiedad y preparar su cuidado."] },
        { heading: "1. Documenta el estado inicial de la propiedad", paragraphs: ["Toma fotografías y videos con fecha de habitaciones, acabados, equipos, instalaciones visibles y áreas exteriores. Registra detalles que puedan ser útiles para comparar cambios posteriores.", "Una documentación inicial no sustituye una inspección profesional, pero crea contexto para conversar sobre una incidencia y evita depender de recuerdos o mensajes incompletos."] },
        { heading: "2. Revisa los sistemas básicos", paragraphs: ["Comprueba el aire acondicionado, la iluminación, los contactos y los accesos dentro de lo que sea seguro y visible. Observa fugas, presión, drenajes, agua caliente, bombas, cisterna, llaves y cerraduras.", "Cuando un elemento requiera conocimientos especializados, registra la señal y solicita una evaluación adecuada. El objetivo es identificar pendientes, no improvisar reparaciones."], checklist: ["CLIMATIZACIÓN: aire acondicionado y controles", "AGUA: fugas, presión, drenajes y agua caliente", "ELECTRICIDAD: iluminación, contactos y breakers cuando corresponda", "ACCESOS: cerraduras, llaves y accesos digitales cuando existan", "ACABADOS: humedad, pintura y daños visibles", "EVIDENCIAS: fotos y pendientes registrados"] },
        { heading: "3. Define quién atenderá una incidencia cuando tú no estés", paragraphs: ["Si vives en otra ciudad o país, decide con anticipación quién recibirá una solicitud, quién podrá facilitar el acceso y cómo se compartirán evidencias. Un contacto local reduce la improvisación.", "También conviene definir qué asuntos requieren tu aprobación y qué información debe acompañar una solicitud. Esto ayuda a cuidar el inmueble sin presentar una cobertura que no existe."] },
        { heading: "4. Organiza un historial de mantenimiento", paragraphs: ["Guarda fechas, fotografías, diagnósticos, decisiones y conclusiones. Un historial sencillo permite reconocer repeticiones, priorizar revisiones y entregar mejor contexto a un nuevo técnico o administrador.", "La organización documental es especialmente útil cuando la propiedad cambia entre uso personal, vivienda vacía o renta. Mantén el registro conectado con el inmueble y su alcance real."] },
        { heading: "5. Si será rentada, prepárala antes del primer huésped", paragraphs: ["Antes de recibir huéspedes, revisa accesos, climatización, agua, electricidad, mobiliario, humedad y daños visibles. Separa lo que debe atenderse antes de abrir la propiedad de lo que puede programarse.", "No hace falta prometer una operación sin incidentes. Hace falta contar con una base clara para detectar, comunicar y coordinar necesidades cuando aparezcan."] },
        { heading: "6. No esperes a que un problema pequeño se convierta en urgente", paragraphs: ["Una fuga visible, un aire acondicionado con bajo rendimiento o una cerradura que falla pueden complicarse si se ignoran. Registrar temprano la señal permite decidir con más opciones y menos presión.", "Total Solutions puede ayudar a coordinar solicitudes, técnicos, evidencias y conclusión conforme al alcance y disponibilidad del servicio. Solicita apoyo cuando tengas una necesidad concreta."] }
      ] },
      { sections: [
        { heading: "Una señal temprana merece atención", paragraphs: ["El aire acondicionado suele ser central para la comodidad en Cancún. Una alteración gradual puede pasar desapercibida hasta que afecta una habitación, una reserva o la operación diaria.", "Estas señales no sustituyen el diagnóstico de un especialista. Sirven para registrar lo observado y decidir cuándo conviene pedir una revisión."] },
        { heading: "1. Enfría menos o tarda más", paragraphs: ["Si el equipo tarda más en alcanzar una temperatura cómoda o una habitación sigue caliente, puede existir una causa que requiere evaluación. No asumas automáticamente cuál es el problema.", "Registra cuándo ocurre, en qué unidad y bajo qué condiciones. Esa información ayuda a coordinar una visita más útil."] },
        { heading: "2. Aparecen ruidos, vibraciones u olores", paragraphs: ["Ruidos nuevos, vibraciones o un olor diferente pueden indicar que el equipo necesita atención. Apagarlo puede ser prudente si existe una señal de riesgo, humo o daño visible.", "Evita abrir componentes o intervenir instalaciones sin el perfil adecuado. Una fotografía y una descripción concreta son mejores que una reparación improvisada."] },
        { heading: "3. Hay goteo o humedad cerca del equipo", paragraphs: ["El agua alrededor de un minisplit o en una pared cercana merece registro. La humedad puede afectar acabados y otras áreas si no se atiende oportunamente.", "Documenta la ubicación y el momento del hallazgo. Si el goteo es activo o aumenta, trátalo como una incidencia que requiere coordinación prioritaria."] },
        { heading: "4. El flujo de aire es irregular", paragraphs: ["Un flujo débil o desigual puede cambiar la experiencia de una habitación. Compara lo que ocurre con el funcionamiento habitual, sin forzar el equipo ni alterar configuraciones desconocidas.", "Una revisión preventiva puede ayudar a distinguir una observación simple de un problema que requiere diagnóstico especializado."] },
        { heading: "5. El consumo o los ciclos parecen diferentes", paragraphs: ["Si el equipo trabaja durante más tiempo, se enciende y apaga con demasiada frecuencia o presenta un comportamiento distinto, conviene anotarlo. Un solo síntoma no confirma una causa.", "Total Solutions puede coordinar una solicitud, visita, diagnóstico y evidencias según el alcance del servicio. Solicita mantenimiento antes de que una señal afecte a huéspedes o residentes."], checklist: ["Anotar la señal y cuándo aparece", "Tomar fotografías de daños visibles", "No abrir ni reparar componentes sin especialista", "Confirmar acceso y persona autorizada", "Solicitar diagnóstico cuando corresponda", "Guardar la conclusión y evidencias"] }
      ] }
    ],
    en: [],
    "pt-BR": []
  };
  additionalEditorial.en = [
    { sections: [
      { heading: "After-sales is also part of the buyer experience", paragraphs: ["Signing and handing over the keys are important moments, but they do not always close the buyer's practical questions. Adjustments, inspections and decisions can shape how the client experiences the purchase.", "Organized after-sales support does not promise that problems will never happen. It gives the buyer a clear way to record a need, understand the next step and find local support when appropriate."] },
      { heading: "What happens after signing and handover", paragraphs: ["Early needs are often concrete: air conditioning, plumbing, electrical work, paint, locks, small adjustments, preventive maintenance or preparation for a rental. Each property has a different scope and not every issue should be handled the same way.", "When the agency helps organize the information, the buyer can separate an urgent incident from a scheduled improvement. Useful diagnosis and evidence make the decision clearer."] },
      { heading: "The agency does not need to become a maintenance company", paragraphs: ["A real estate agency can remain commercial and relationship-focused. It does not need to execute every repair or assume technical responsibility to keep caring about the buyer experience.", "The goal is to maintain a point of contact and guide the client toward reliable operational support. After-sales is not about solving every problem personally; it is about making sure the client knows where to turn."] },
      { heading: "What a good after-sales strategy can organize", paragraphs: ["A simple procedure can define who receives a request, what information should be shared, how a visit is coordinated and what follows diagnosis. It should also explain what requires approval and what evidence will be delivered."], checklist: ["Clear maintenance contact", "Procedure for recording incidents", "Criteria for requesting diagnosis", "Approval of scope before execution", "Evidence and service conclusion", "History of needs when appropriate"] },
      { heading: "Buyers who live away from Cancún", paragraphs: ["Investors, international buyers and second-home owners may need local support without being available for every visit. Knowing what was found and what was done matters as much as finding the right person.", "Communication should remain concrete and realistic. This is not a claim of permanent monitoring or guaranteed outcomes, but a documented path for specific needs."] },
      { heading: "How Total Solutions can participate", paragraphs: ["Total Solutions can support request, coordination and supervision, connect the right technician, organize diagnosis, follow up and document evidence through conclusion, with warranty when applicable.", "The agency keeps its relationship with the buyer and can offer a local option without becoming a maintenance company. If you want to strengthen your clients' after-sales experience, talk with Total Solutions."] }
    ] },
    { sections: [
      { heading: "Buying the property is the beginning", paragraphs: ["After buying an investment property in Cancún, it helps to move from the initial excitement to practical organization. The property needs a documented starting point, clear responsibilities and a way to decide what to handle first.", "This is not advice about returns, taxes or legal matters. It is an operational guide to understanding the property's physical condition and preparing its care."] },
      { heading: "1. Document the property's initial condition", paragraphs: ["Take dated photos and videos of rooms, finishes, visible equipment, installations and outdoor areas. Record details that may help compare later changes.", "Initial documentation does not replace a professional inspection, but it creates context for an incident and avoids relying on memory or incomplete messages."] },
      { heading: "2. Review the basic systems", paragraphs: ["Check air conditioning, lighting, outlets and access where it is safe and visible. Observe leaks, pressure, drains, hot water, pumps, cisterns, keys and locks.", "When an element requires specialist knowledge, record the signal and request an appropriate evaluation. The goal is to identify open items, not improvise repairs."], checklist: ["CLIMATE: air conditioning and controls", "WATER: leaks, pressure, drains and hot water", "ELECTRICITY: lighting, outlets and breakers when applicable", "ACCESS: locks, keys and digital access when available", "FINISHES: humidity, paint and visible damage", "EVIDENCE: photos and recorded open items"] },
      { heading: "3. Decide who will handle incidents when you are away", paragraphs: ["If you live in another city or country, decide who receives a request, who can provide access and how evidence will be shared. A local contact reduces improvisation.", "Also define which matters require your approval and what information belongs in a request. This helps care for the property without suggesting coverage that does not exist."] },
      { heading: "4. Keep a maintenance history", paragraphs: ["Save dates, photos, diagnoses, decisions and conclusions. A simple history helps identify repetitions, prioritize inspections and give better context to a new technician or manager.", "Documentation is especially useful when a property moves between personal use, vacancy and rental. Keep the record connected to the property and its real scope."] },
      { heading: "5. If it will be rented, prepare it before the first guest", paragraphs: ["Before welcoming guests, review access, climate control, water, electricity, furniture, humidity and visible damage. Separate what must be handled before opening from what can be scheduled.", "There is no need to promise an incident-free operation. The important thing is a clear base for detecting, communicating and coordinating needs."] },
      { heading: "6. Do not wait for a small issue to become urgent", paragraphs: ["A visible leak, weak air conditioning or failing lock can become more complicated when ignored. Recording it early creates more options and less pressure.", "Total Solutions can help coordinate requests, technicians, evidence and conclusion according to service scope and availability. Request support when you have a concrete need."] }
    ] },
    { sections: [
      { heading: "An early signal deserves attention", paragraphs: ["Air conditioning is central to comfort in Cancún. A gradual change can go unnoticed until it affects a room, a reservation or daily operations.", "These signals do not replace a specialist diagnosis. They help you record what you observed and decide when a review makes sense."] },
      { heading: "1. It cools less or takes longer", paragraphs: ["If the unit takes longer to reach a comfortable temperature or a room stays warm, a cause may need evaluation. Do not assume the diagnosis automatically.", "Record when it happens, in which unit and under what conditions. This makes a coordinated visit more useful."] },
      { heading: "2. New noises, vibration or odors appear", paragraphs: ["New sounds, vibration or a different odor can signal that the unit needs attention. Turn it off if there is a risk signal, smoke or visible damage.", "Avoid opening components or changing installations without the right profile. A photo and concrete description are better than an improvised repair."] },
      { heading: "3. There is dripping or moisture near the unit", paragraphs: ["Water around a mini-split or on a nearby wall deserves a record. Moisture can affect finishes and other areas if it is not addressed promptly.", "Document the location and time of the finding. If dripping is active or increasing, treat it as an incident requiring priority coordination."] },
      { heading: "4. Airflow is uneven", paragraphs: ["Weak or uneven airflow can change the experience of a room. Compare it with normal operation without forcing the unit or changing unknown settings.", "A preventive review can help distinguish a simple observation from an issue requiring specialist diagnosis."] },
      { heading: "5. Consumption or cycles seem different", paragraphs: ["If the unit runs longer, turns on and off too often or behaves differently, note it. One symptom does not confirm a cause.", "Total Solutions can coordinate a request, visit, diagnosis and evidence according to service scope. Request maintenance before a signal affects guests or residents."], checklist: ["Note the signal and when it appears", "Photograph visible damage", "Do not open or repair components without a specialist", "Confirm access and an authorized person", "Request diagnosis when appropriate", "Keep the conclusion and evidence"] }
    ] }
  ];
  additionalEditorial["pt-BR"] = [
    { sections: [
      { heading: "O pós-venda também faz parte da experiência", paragraphs: ["A assinatura e a entrega das chaves são momentos importantes, mas nem sempre encerram as dúvidas práticas do comprador. Ajustes, revisões e decisões podem influenciar a percepção sobre a compra.", "Um pós-venda organizado não promete que problemas nunca acontecerão. Ele oferece um caminho claro para registrar uma necessidade, entender o próximo passo e encontrar apoio local quando fizer sentido."] },
      { heading: "O que acontece depois da assinatura e da entrega", paragraphs: ["As primeiras necessidades costumam ser concretas: ar-condicionado, hidráulica, elétrica, pintura, fechaduras, pequenos ajustes, manutenção preventiva ou preparação para locação. Cada imóvel tem um escopo diferente.", "Quando a imobiliária ajuda a organizar as informações, o comprador consegue separar uma ocorrência urgente de uma melhoria programável. Diagnóstico e evidências úteis tornam a decisão mais clara."] },
      { heading: "A imobiliária não precisa virar uma empresa de manutenção", paragraphs: ["A imobiliária pode continuar focada no relacionamento e na atividade comercial. Não precisa executar cada reparo nem assumir responsabilidade técnica para continuar cuidando da experiência do comprador.", "O objetivo é manter um ponto de contato e orientar o cliente para um apoio operacional confiável. Pós-venda não é resolver pessoalmente cada problema; é garantir que o cliente saiba a quem recorrer."] },
      { heading: "O que uma boa estratégia de pós-venda pode organizar", paragraphs: ["Um procedimento simples pode definir quem recebe a solicitação, quais informações devem ser compartilhadas, como uma visita é coordenada e o que acontece depois do diagnóstico. Também deve explicar o que exige aprovação e quais evidências serão entregues."], checklist: ["Contato claro para manutenção", "Procedimento para registrar ocorrências", "Critérios para solicitar diagnóstico", "Aprovação do escopo antes da execução", "Evidências e conclusão do serviço", "Histórico das necessidades quando aplicável"] },
      { heading: "Compradores que vivem longe de Cancún", paragraphs: ["Investidores, compradores internacionais e proprietários de segunda residência podem precisar de apoio local sem estar disponíveis para cada visita. Saber o que foi encontrado e feito é tão importante quanto encontrar a pessoa certa.", "A comunicação deve ser concreta e realista. Não é uma promessa de monitoramento permanente ou resultado garantido, mas um caminho documentado para necessidades específicas."] },
      { heading: "Como a Total Solutions pode participar", paragraphs: ["A Total Solutions pode apoiar solicitação, coordenação e supervisão, conectar o técnico adequado, organizar o diagnóstico, acompanhar e documentar evidências até a conclusão, com garantia quando aplicável.", "A imobiliária mantém sua relação com o comprador e pode oferecer uma opção local sem virar uma empresa de manutenção. Se quiser fortalecer o pós-venda dos seus clientes, fale com a Total Solutions."] }
    ] },
    { sections: [
      { heading: "Comprar o imóvel é o começo", paragraphs: ["Depois de comprar um imóvel de investimento em Cancún, vale passar da empolgação inicial para uma organização prática. O imóvel precisa de um ponto de partida documentado, responsabilidades claras e uma forma de decidir o que atender primeiro.", "Este não é um aconselhamento sobre retorno, impostos ou questões jurídicas. É um guia operacional para conhecer o estado físico do imóvel e preparar seu cuidado."] },
      { heading: "1. Documente o estado inicial do imóvel", paragraphs: ["Faça fotos e vídeos datados dos cômodos, acabamentos, equipamentos visíveis, instalações e áreas externas. Registre detalhes que ajudem a comparar mudanças depois.", "A documentação inicial não substitui uma inspeção profissional, mas cria contexto para uma ocorrência e evita depender da memória ou de mensagens incompletas."] },
      { heading: "2. Revise os sistemas básicos", paragraphs: ["Confira ar-condicionado, iluminação, tomadas e acessos onde for seguro e visível. Observe vazamentos, pressão, ralos, água quente, bombas, cisterna, chaves e fechaduras.", "Quando um item exigir conhecimento especializado, registre o sinal e solicite uma avaliação adequada. O objetivo é identificar pendências, não improvisar reparos."], checklist: ["CLIMATIZAÇÃO: ar-condicionado e controles", "ÁGUA: vazamentos, pressão, ralos e água quente", "ELÉTRICA: iluminação, tomadas e disjuntores quando aplicável", "ACESSOS: fechaduras, chaves e acessos digitais quando existirem", "ACABAMENTOS: umidade, pintura e danos visíveis", "EVIDÊNCIAS: fotos e pendências registradas"] },
      { heading: "3. Defina quem atenderá uma ocorrência quando você não estiver", paragraphs: ["Se você mora em outra cidade ou país, decida quem recebe uma solicitação, quem pode liberar o acesso e como as evidências serão compartilhadas. Um contato local reduz improvisos.", "Defina também quais assuntos exigem sua aprovação e quais informações devem acompanhar uma solicitação. Isso ajuda a cuidar do imóvel sem sugerir uma cobertura que não existe."] },
      { heading: "4. Organize um histórico de manutenção", paragraphs: ["Guarde datas, fotos, diagnósticos, decisões e conclusões. Um histórico simples ajuda a reconhecer repetições, priorizar revisões e oferecer contexto a um novo técnico ou gestor.", "A documentação é especialmente útil quando o imóvel alterna entre uso pessoal, vazio e locação. Mantenha o registro ligado ao imóvel e ao seu escopo real."] },
      { heading: "5. Se for alugar, prepare antes do primeiro hóspede", paragraphs: ["Antes de receber hóspedes, revise acessos, climatização, água, elétrica, móveis, umidade e danos visíveis. Separe o que precisa ser atendido antes da abertura do que pode ser programado.", "Não é necessário prometer uma operação sem ocorrências. O importante é ter uma base clara para detectar, comunicar e coordenar necessidades."] },
      { heading: "6. Não espere um problema pequeno virar urgente", paragraphs: ["Um vazamento visível, ar-condicionado fraco ou fechadura com falha pode se complicar quando ignorado. Registrar cedo cria mais opções e menos pressão.", "A Total Solutions pode ajudar a coordenar solicitações, técnicos, evidências e conclusão conforme o escopo e a disponibilidade. Solicite apoio quando houver uma necessidade concreta."] }
    ] },
    { sections: [
      { heading: "Um sinal inicial merece atenção", paragraphs: ["O ar-condicionado é central para o conforto em Cancún. Uma mudança gradual pode passar despercebida até afetar um cômodo, uma reserva ou a operação diária.", "Estes sinais não substituem o diagnóstico de um especialista. Eles ajudam a registrar o que foi observado e decidir quando vale pedir uma revisão."] },
      { heading: "1. Resfria menos ou demora mais", paragraphs: ["Se o equipamento demora mais para chegar a uma temperatura confortável ou um cômodo continua quente, pode haver uma causa que precisa de avaliação. Não presuma o diagnóstico.", "Registre quando acontece, em qual unidade e em quais condições. Isso torna a visita coordenada mais útil."] },
      { heading: "2. Surgem ruídos, vibrações ou odores", paragraphs: ["Ruídos novos, vibração ou um odor diferente podem indicar que o equipamento precisa de atenção. Desligue-o se houver sinal de risco, fumaça ou dano visível.", "Evite abrir componentes ou alterar instalações sem o perfil adequado. Uma foto e uma descrição objetiva são melhores que um reparo improvisado."] },
      { heading: "3. Há gotejamento ou umidade perto do equipamento", paragraphs: ["Água ao redor de um split ou em uma parede próxima merece registro. A umidade pode afetar acabamentos e outras áreas se não for tratada a tempo.", "Documente o local e o momento da descoberta. Se o gotejamento estiver ativo ou aumentando, trate como ocorrência que requer coordenação prioritária."] },
      { heading: "4. O fluxo de ar está irregular", paragraphs: ["Um fluxo fraco ou desigual pode mudar a experiência de um cômodo. Compare com o funcionamento normal sem forçar o equipamento ou alterar configurações desconhecidas.", "Uma revisão preventiva ajuda a distinguir uma observação simples de um problema que exige diagnóstico especializado."] },
      { heading: "5. O consumo ou os ciclos parecem diferentes", paragraphs: ["Se o equipamento funciona por mais tempo, liga e desliga com muita frequência ou se comporta de outra forma, anote. Um sintoma isolado não confirma uma causa.", "A Total Solutions pode coordenar solicitação, visita, diagnóstico e evidências conforme o escopo. Solicite manutenção antes que o sinal afete hóspedes ou moradores."], checklist: ["Anotar o sinal e quando aparece", "Fotografar danos visíveis", "Não abrir ou reparar componentes sem especialista", "Confirmar acesso e pessoa autorizada", "Solicitar diagnóstico quando aplicável", "Guardar conclusão e evidências"] }
    ] }
  ];
  const additionalCta = {
    es: [
      { ctaTitle: "¿Quieres fortalecer la experiencia posventa de tus clientes?", ctaText: "Conoce una forma clara de orientar solicitudes y apoyo operativo después de la compra.", ctaLabel: "Hablar con Total Solutions", ctaSecondaryLabel: "Conocer cómo funciona", ctaSecondaryUrl: "/como-funciona", whatsappMessage: "Hola, represento una inmobiliaria / equipo de ventas y me gustaría conocer cómo Total Solutions puede apoyar la atención posventa de nuestros clientes." },
      { ctaTitle: "¿Ya compraste una propiedad de inversión?", ctaText: "Organiza el estado inicial, el mantenimiento y la atención de incidencias con información clara.", ctaLabel: "Solicitar un servicio", whatsappMessage: "Hola, compré una propiedad de inversión en Cancún y me gustaría conocer opciones para organizar su mantenimiento." },
      { ctaTitle: "¿Tu aire acondicionado muestra alguna de estas señales?", ctaText: "Coordina una revisión antes de que una señal afecte a residentes o huéspedes.", ctaLabel: "Solicitar mantenimiento", whatsappMessage: "Hola, quiero solicitar una revisión de aire acondicionado en una propiedad de Cancún." }
    ],
    en: [
      { ctaTitle: "Want to strengthen your clients' after-sales experience?", ctaText: "Learn a clear way to guide requests and operational support after the purchase.", ctaLabel: "Talk with Total Solutions", ctaSecondaryLabel: "See how it works", ctaSecondaryUrl: "/como-funciona", whatsappMessage: "Hello, I represent a real estate agency / sales team and would like to learn how Total Solutions can support our clients after the purchase." },
      { ctaTitle: "Have you bought an investment property?", ctaText: "Organize its initial condition, maintenance and incident response with clear information.", ctaLabel: "Request a service", whatsappMessage: "Hello, I bought an investment property in Cancún and would like to learn about ways to organize its maintenance." },
      { ctaTitle: "Is your air conditioner showing one of these signs?", ctaText: "Coordinate a review before a signal affects residents or guests.", ctaLabel: "Request maintenance", whatsappMessage: "Hello, I would like to request an air-conditioning review at a property in Cancún." }
    ],
    "pt-BR": [
      { ctaTitle: "Quer fortalecer o pós-venda dos seus clientes?", ctaText: "Conheça uma forma clara de orientar solicitações e apoio operacional depois da compra.", ctaLabel: "Falar com a Total Solutions", ctaSecondaryLabel: "Conhecer como funciona", ctaSecondaryUrl: "/como-funciona", whatsappMessage: "Olá, represento uma imobiliária / equipe de vendas e gostaria de saber como a Total Solutions pode apoiar o pós-venda dos nossos clientes." },
      { ctaTitle: "Você comprou um imóvel de investimento?", ctaText: "Organize o estado inicial, a manutenção e o atendimento de ocorrências com informação clara.", ctaLabel: "Solicitar um serviço", whatsappMessage: "Olá, comprei um imóvel de investimento em Cancún e gostaria de conhecer opções para organizar a manutenção." },
      { ctaTitle: "Seu ar-condicionado apresenta algum destes sinais?", ctaText: "Coordene uma revisão antes que um sinal afete moradores ou hóspedes.", ctaLabel: "Solicitar manutenção", whatsappMessage: "Olá, gostaria de solicitar uma revisão de ar-condicionado em um imóvel em Cancún." }
    ]
  };
  Object.assign(copy.es.categories, { inmobiliarias: "Inmobiliarias", investment: "Inversión inmobiliaria", airconditioning: "Aire acondicionado" });
  Object.assign(copy.en.categories, { inmobiliarias: "Real Estate Agencies", investment: "Real Estate Investment", airconditioning: "Air conditioning" });
  Object.assign(copy["pt-BR"].categories, { inmobiliarias: "Imobiliárias", investment: "Investimento imobiliário", airconditioning: "Ar-condicionado" });
  Object.assign(copy.es.labels, { inmobiliarias: "Corredor inmobiliario entrega las llaves de una propiedad en Cancún mientras un técnico acompaña el servicio posventa", investment: "Propietario revisa con un técnico el estado y mantenimiento de una propiedad de inversión en Cancún", airconditioning: "Técnico inspecciona un aire acondicionado en una propiedad de Cancún mientras el propietario observa la revisión" });
  Object.assign(copy.en.labels, { inmobiliarias: "Real estate agent hands over property keys in Cancún while a technician supports after-sales service", investment: "Property owner reviews the condition and maintenance of an investment property in Cancún with a technician", airconditioning: "Technician inspects an air conditioner at a Cancún property while the owner observes the maintenance check" });
  Object.assign(copy["pt-BR"].labels, { inmobiliarias: "Corretor entrega as chaves de um imóvel em Cancún enquanto um técnico apoia o pós-venda", investment: "Proprietário revisa com um técnico o estado e a manutenção de um imóvel de investimento em Cancún", airconditioning: "Técnico inspeciona um ar-condicionado em um imóvel em Cancún enquanto o proprietário acompanha a revisão" });
  languages.forEach(locale => {
    copy[locale].articles.push(...additionalCopy[locale]);
    editorial[locale].push(...additionalEditorial[locale]);
    cta[locale].push(...additionalCta[locale]);
  });

  const localizedArticle = index => { const c = currentCopy(); const article = editorial[lang][index] || {}; return { ...meta[index], ...c.articles[index], ...article, ...cta[lang][index], categoryLabel: c.categories[meta[index].category], image_alt: c.labels[meta[index].category], author: "Total Solutions Cancún" }; };
  const card = article => { const c = currentCopy(); return `<article class="blog-card"><img class="blog-card-image-editorial" src="${article.hero_image}" alt="${esc(article.image_alt)}" width="${article.width}" height="${article.height}" loading="lazy"><div class="blog-card-body"><p class="blog-category">${esc(article.categoryLabel)}</p><h3>${esc(article.title)}</h3><p>${esc(article.description)}</p><p class="blog-meta">${esc(article.author)} · ${article.minutes} ${esc(c.readTime)} · ${article.date}</p><a class="blog-link" href="${articleUrl(article)}">${esc(c.read)} <span aria-hidden="true">→</span></a></div></article>`; };
  const sectionMarkup = section => `<section><h2>${esc(section.heading)}</h2>${(section.paragraphs || []).map(paragraph => `<p>${esc(paragraph)}</p>`).join("")}${section.checklist ? `<ul>${section.checklist.map(item => `<li>${esc(item)}</li>`).join("")}</ul>` : ""}</section>`;
  const shell = (title, text, content) => `${nav()}<header class="blog-hero"><div class="blog-hero-inner"><p class="public-kicker">Total Solutions Cancún</p><h1>${esc(title)}</h1><p>${esc(text)}</p></div></header><main class="blog-content">${content}</main>${footer()}`;
  let globalEventsBound = false;
  const setLanguage = value => { lang = normalizeLanguage(value); localStorage.setItem(languageKey, lang); updateDocumentLanguage(); render(); };
  const bindNav = () => { const menu = document.querySelector(".public-menu"); const links = document.getElementById("blogPublicLinks"); if (menu && links) menu.addEventListener("click", () => { const open = links.classList.toggle("is-open"); menu.setAttribute("aria-expanded", String(open)); menu.textContent = open ? "×" : "☰"; menu.setAttribute("aria-label", open ? currentCopy().close : currentCopy().menu); }); if (!globalEventsBound) { document.addEventListener("click", event => { const button = event.target.closest("[data-lang]"); if (button) setLanguage(button.dataset.lang); }); globalEventsBound = true; } };
  const updateDocumentLanguage = () => { document.documentElement.lang = lang === "pt-BR" ? "pt-BR" : `${lang}-MX`; };
  const renderIndex = () => { const c = currentCopy(); const articles = meta.map((_, index) => localizedArticle(index)); const title = "Blog"; const description = lang === "en" ? "Practical ideas about professional maintenance for properties, hotels, Airbnb and investments in Cancún." : lang === "pt-BR" ? "Ideias práticas sobre manutenção profissional para imóveis, hotéis, Airbnb e investimentos em Cancún." : "Ideas prácticas sobre mantenimiento profesional para propiedades, hoteles, Airbnb e inversiones en Cancún."; document.title = `${title} | Total Solutions Cancún`; setMeta('meta[name="description"]', description); setSchema({ "@context": "https://schema.org", "@type": "CollectionPage", name: title, description, url: "https://totalsolutionscancun.com/blog", inLanguage: lang, mainEntity: articles.map(article => ({ "@type": "Article", headline: article.title, url: `https://totalsolutionscancun.com${articleUrl(article)}`, image: [`https://totalsolutionscancun.com${article.hero_image}`], author: { "@type": "Organization", name: article.author }, datePublished: article.date })) }); const filters = ["all", ...new Set(meta.map(article => article.category))]; document.body.innerHTML = shell(title, c.intro, `<div class="blog-toolbar"><div><h2>${esc(c.context)}</h2></div><p>${esc(c.toolbar)}</p></div><div class="blog-filters" role="group" aria-label="${esc(c.context)}">${filters.map((filter, index) => `<button type="button" class="blog-filter" data-filter="${filter}" aria-pressed="${index === 0}">${esc(filter === "all" ? c.all : c.categories[filter])}</button>`).join("")}</div><div class="blog-grid">${articles.map(card).join("")}</div>`); bindNav(); document.querySelectorAll(".blog-filter").forEach(button => button.addEventListener("click", () => { const filter = button.dataset.filter; document.querySelectorAll(".blog-filter").forEach(item => item.setAttribute("aria-pressed", String(item === button))); document.querySelectorAll(".blog-card").forEach((item, index) => { item.hidden = filter !== "all" && meta[index].category !== filter; }); })); };
  const renderPost = index => { const c = currentCopy(); const article = localizedArticle(index); const url = `https://totalsolutionscancun.com${articleUrl(article)}`; const whatsappUrl = `https://wa.me/529984078199?text=${encodeURIComponent(article.whatsappMessage)}`; document.title = `${article.title} | Total Solutions Cancún`; updateDocumentLanguage(); setMeta('meta[name="description"]', article.description); document.querySelector('link[rel="canonical"]').href = url; setMeta('meta[property="og:title"]', article.title); setMeta('meta[property="og:description"]', article.description); setMeta('meta[property="og:url"]', url); setMeta('meta[property="og:image"]', `https://totalsolutionscancun.com${article.hero_image}`); setSchema({ "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, image: [`https://totalsolutionscancun.com${article.hero_image}`], inLanguage: lang, author: { "@type": "Organization", name: article.author }, publisher: { "@type": "Organization", name: "Total Solutions Cancún", logo: { "@type": "ImageObject", url: "https://totalsolutionscancun.com/assets/assets/total-solutions-logo.svg" } }, datePublished: article.date, dateModified: article.date, mainEntityOfPage: { "@type": "WebPage", "@id": url } }); const secondaryCta = article.ctaSecondaryLabel ? `<a href="${article.ctaSecondaryUrl}">${esc(article.ctaSecondaryLabel)}</a>` : ""; const body = `<a class="blog-back" href="/blog">${esc(c.back)}</a><article class="blog-article"><p class="blog-category">${esc(article.categoryLabel)}</p><h1>${esc(article.title)}</h1><p class="blog-dek">${esc(article.description)}</p><p class="blog-meta">${esc(article.author)} · ${article.minutes} ${esc(c.readTime)} · ${article.date}</p><figure><img class="blog-card-image-editorial" src="${article.hero_image}" alt="${esc(article.image_alt)}" width="${article.width}" height="${article.height}" loading="eager"><figcaption>Total Solutions Cancún · ${esc(c.footer)}</figcaption></figure>${article.sections.map(sectionMarkup).join("")}<div class="public-callout"><div><h2>${esc(article.ctaTitle)}</h2><p>${esc(article.ctaText)}</p></div><a href="/solicitar-servico">${esc(article.ctaLabel)}</a>${secondaryCta}<a href="${whatsappUrl}" target="_blank" rel="noopener">${esc(c.whatsapp)}</a></div></article><section class="blog-related"><h2>${esc(c.related)}</h2><div class="blog-grid">${meta.map((_, relatedIndex) => relatedIndex).filter(relatedIndex => relatedIndex !== index).map(relatedIndex => card(localizedArticle(relatedIndex))).join("")}</div></section>`; document.body.innerHTML = shell(article.title, article.description, body); bindNav(); };
  const renderNotFound = () => { const c = currentCopy(); document.title = `${c.notFound} | Total Solutions Cancún`; updateDocumentLanguage(); document.body.innerHTML = shell(c.notFound, c.notFoundText, `<p>${esc(c.notFoundHelp)} <a class="blog-link" href="/blog">Blog</a>.</p>`); bindNav(); };
  const render = () => { if (document.body.dataset.blogPage === "post" && index >= 0) renderPost(index); else if (document.body.dataset.blogPage === "post") renderNotFound(); else renderIndex(); };
  const slug = decodeURIComponent(location.pathname.replace(/^\/blog\/?/, "").replace(/\/$/, ""));
  const index = meta.findIndex(article => article.slug === slug);
  updateDocumentLanguage();
  render();
})();
