(() => {
  const languageKey = "totalsolutions_public_language";
  const image = "/static/images/total-solutions-social-1200x630.png";
  const languages = ["es", "en", "pt-BR"];
  const copy = {
    es: {
      navAbout: "Quiénes somos", navHow: "Cómo funciona", navFaq: "Preguntas frecuentes", navRequest: "Solicitar servicio", menu: "Abrir menú", close: "Cerrar menú", back: "Volver al blog", read: "Leer artículo", readTime: "min de lectura", related: "También puede interesarte", all: "Todos", context: "Contenido por contexto", intro: "Ideas para cuidar mejor una propiedad y coordinar mantenimiento con más claridad.", toolbar: "Perspectivas prácticas para brokers, propietarios, inversionistas, Airbnb y administradores.", footer: "Mantenimiento profesional y seguimiento operativo en Cancún.", whatsapp: "Hablar por WhatsApp", request: "Solicitar un servicio", requestText: "Coordinamos la solicitud, la visita y el seguimiento.", notFound: "Artículo no encontrado", notFoundText: "El contenido solicitado no está disponible.", notFoundHelp: "Consulta los artículos disponibles en el Blog.", categories: { brokers: "Brokers / Inmobiliarias", owners: "Propietarios / Inversionistas", airbnb: "Airbnb / Property Managers" }, labels: { brokers: "Broker entrega las llaves de una propiedad mientras un técnico da continuidad al mantenimiento", owners: "Propietario supervisa a distancia el mantenimiento de una propiedad en Cancún", airbnb: "Anfitrión supervisa el mantenimiento preventivo de una propiedad de renta vacacional en Cancún mientras un técnico realiza una inspección" }, articles: [
        { title: "¿Quién cuida la propiedad después de entregar las llaves?", description: "La entrega no termina la responsabilidad operativa: una red confiable mantiene la propiedad lista para su siguiente etapa.", sections: [["La operación continúa después de la venta", "Cuando una propiedad cambia de manos, aparecen tareas que no siempre caben en la agenda del propietario: revisiones, reparaciones, instalaciones y evidencias."], ["Un respaldo para brokers e inmobiliarias", "La coordinación profesional permite registrar la solicitud, entender el alcance, asignar el perfil adecuado y documentar el resultado."], ["Una experiencia más confiable para el propietario", "La propiedad recibe atención organizada y el cliente conserva visibilidad sobre el proceso."]] },
        { title: "Cómo cuidar una propiedad en Cancún cuando vives en otra ciudad o país", description: "Mantenimiento coordinado, evidencias y seguimiento para propietarios que necesitan operar a distancia.", sections: [["La distancia aumenta el costo de la incertidumbre", "Cuando el propietario no está en Cancún, un problema pequeño puede crecer antes de ser visto. La prioridad es contar con información clara y evidencia."], ["De la solicitud a la conclusión", "Un flujo ordenado conecta solicitud, diagnóstico, supervisión, técnico, evidencias y conclusión."], ["Una red local con visibilidad", "El respaldo local facilita decidir a tiempo y mantener el control sin estar físicamente en el inmueble."]] },
        { title: "Mantenimiento preventivo para Airbnb y renta vacacional en Cancún", description: "Una agenda preventiva protege la experiencia del huésped y reduce interrupciones operativas.", sections: [["Prevenir es proteger la operación", "En una renta vacacional, una falla afecta al huésped, la disponibilidad y la reputación del inmueble."], ["Qué conviene observar", "Instalaciones, equipos, humedad, filtraciones y accesorios merecen una revisión adaptada al tipo de propiedad."], ["Evidencia para decidir mejor", "Fotos, diagnóstico y conclusión permiten comparar necesidades y priorizar intervenciones."]] }
      ]
    },
    en: {
      navAbout: "About us", navHow: "How it works", navFaq: "FAQ", navRequest: "Request service", menu: "Open menu", close: "Close menu", back: "Back to blog", read: "Read article", readTime: "min read", related: "You may also be interested", all: "All", context: "Content by context", intro: "Practical ideas for caring for a property and coordinating maintenance with greater clarity.", toolbar: "Practical perspectives for brokers, property owners, investors, Airbnb hosts and managers.", footer: "Professional maintenance and operational tracking in Cancún.", whatsapp: "Chat on WhatsApp", request: "Request a service", requestText: "We coordinate the request, visit and follow-up.", notFound: "Article not found", notFoundText: "The requested content is not available.", notFoundHelp: "Browse the available articles in the Blog.", categories: { brokers: "Brokers / Real Estate Agencies", owners: "Property Owners / Investors", airbnb: "Airbnb / Property Managers" }, labels: { brokers: "Broker hands over property keys while a technician continues the maintenance care", owners: "Property owner remotely oversees the maintenance of a property in Cancún", airbnb: "Host oversees preventive maintenance at a vacation rental in Cancún while a technician performs an inspection" }, articles: [
        { title: "Who takes care of the property after the keys are handed over?", description: "Handover does not end operational responsibility: a trusted network keeps the property ready for its next stage.", sections: [["Operations continue after the sale", "When a property changes hands, tasks arise that do not always fit the owner's schedule: inspections, repairs, installations and evidence."], ["A reliable partner for brokers and real estate agencies", "Professional coordination records the request, clarifies its scope, assigns the right profile and documents the outcome."], ["A more reliable experience for the owner", "The property receives organized attention while the client retains visibility throughout the process."]] },
        { title: "How to take care of a property in Cancún when you live in another city or country", description: "Coordinated maintenance, evidence and follow-up for owners who need to operate remotely.", sections: [["Distance increases the cost of uncertainty", "When an owner is not in Cancún, a small issue can grow before it is seen. Clear information and evidence are the priority."], ["From request to conclusion", "An organized flow connects the request, diagnosis, supervision, technician, evidence and conclusion."], ["A local network with visibility", "Local support helps owners make timely decisions and stay in control without being physically at the property."]] },
        { title: "Preventive maintenance for Airbnb and vacation rentals in Cancún", description: "A preventive schedule protects the guest experience and reduces operational interruptions.", sections: [["Prevention protects the operation", "In a vacation rental, a failure affects the guest, availability and the property's reputation."], ["What deserves attention", "Installations, equipment, humidity, leaks and fixtures deserve a review adapted to the property type."], ["Evidence for better decisions", "Photos, diagnosis and conclusion make it easier to compare needs and prioritize interventions."]] }
      ]
    },
    "pt-BR": {
      navAbout: "Quem somos", navHow: "Como funciona", navFaq: "Perguntas frequentes", navRequest: "Solicitar serviço", menu: "Abrir menu", close: "Fechar menu", back: "Voltar ao blog", read: "Ler artigo", readTime: "min de leitura", related: "Você também pode se interessar", all: "Todos", context: "Conteúdo por contexto", intro: "Ideias práticas para cuidar melhor de um imóvel e coordenar a manutenção com mais clareza.", toolbar: "Perspectivas práticas para corretores, proprietários, investidores, Airbnb e gestores.", footer: "Manutenção profissional e acompanhamento operacional em Cancún.", whatsapp: "Falar pelo WhatsApp", request: "Solicitar um serviço", requestText: "Coordenamos a solicitação, a visita e o acompanhamento.", notFound: "Artigo não encontrado", notFoundText: "O conteúdo solicitado não está disponível.", notFoundHelp: "Consulte os artigos disponíveis no Blog.", categories: { brokers: "Corretores / Imobiliárias", owners: "Proprietários / Investidores", airbnb: "Airbnb / Gestores de propriedades" }, labels: { brokers: "Corretor entrega as chaves de um imóvel enquanto um técnico dá continuidade à manutenção", owners: "Proprietário acompanha remotamente a manutenção de um imóvel em Cancún", airbnb: "Anfitrião acompanha a manutenção preventiva de um imóvel de temporada em Cancún enquanto um técnico realiza uma inspeção" }, articles: [
        { title: "Quem cuida do imóvel depois da entrega das chaves?", description: "A entrega não encerra a responsabilidade operacional: uma rede confiável mantém o imóvel pronto para a próxima etapa.", sections: [["A operação continua depois da venda", "Quando um imóvel muda de mãos, surgem tarefas que nem sempre cabem na agenda do proprietário: revisões, reparos, instalações e evidências."], ["Um apoio para corretores e imobiliárias", "A coordenação profissional registra a solicitação, entende o escopo, atribui o perfil adequado e documenta o resultado."], ["Uma experiência mais confiável para o proprietário", "O imóvel recebe atendimento organizado e o cliente mantém visibilidade sobre o processo."]] },
        { title: "Como cuidar de um imóvel em Cancún morando em outra cidade ou país", description: "Manutenção coordenada, evidências e acompanhamento para proprietários que precisam operar à distância.", sections: [["A distância aumenta o custo da incerteza", "Quando o proprietário não está em Cancún, um problema pequeno pode crescer antes de ser percebido. Informação clara e evidências são a prioridade."], ["Da solicitação à conclusão", "Um fluxo organizado conecta solicitação, diagnóstico, supervisão, técnico, evidências e conclusão."], ["Uma rede local com visibilidade", "O apoio local facilita decisões no momento certo e mantém o controle sem estar fisicamente no imóvel."]] },
        { title: "Manutenção preventiva para Airbnb e aluguel por temporada em Cancún", description: "Uma agenda preventiva protege a experiência do hóspede e reduz interrupções operacionais.", sections: [["Prevenir é proteger a operação", "Em uma locação por temporada, uma falha afeta o hóspede, a disponibilidade e a reputação do imóvel."], ["O que merece atenção", "Instalações, equipamentos, umidade, vazamentos e acessórios merecem uma revisão adaptada ao tipo de imóvel."], ["Evidências para decidir melhor", "Fotos, diagnóstico e conclusão ajudam a comparar necessidades e priorizar intervenções."]] }
      ]
    }
  };
  const meta = [
    { slug: "quien-cuida-propiedad-despues-de-la-venta", category: "brokers", minutes: 5, date: "2026-09-11", hero_image: "/assets/blog/images/quien-cuida-propiedad-despues-de-la-venta.jpg", width: 1200, height: 900 },
    { slug: "cuidar-propiedad-cancun-desde-el-extranjero", category: "owners", minutes: 6, date: "2026-09-11", hero_image: "/assets/blog/images/cuidar-propiedad-cancun-desde-el-extranjero.jpg", width: 1200, height: 900 },
    { slug: "mantenimiento-preventivo-airbnb-cancun", category: "airbnb", minutes: 5, date: "2026-09-11", hero_image: "/assets/blog/images/mantenimiento-preventivo-airbnb-cancun.jpg", width: 1200, height: 900 }
  ];
  const esc = value => String(value).replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
  const normalizeLanguage = value => String(value || "").toLowerCase().startsWith("pt") ? "pt-BR" : String(value || "").toLowerCase().startsWith("en") ? "en" : "es";
  let lang = normalizeLanguage(new URLSearchParams(location.search).get("lang") || localStorage.getItem(languageKey) || navigator.language);
  const currentCopy = () => copy[lang];
  const articleUrl = article => `/blog/${article.slug}`;
  const nav = () => { const c = currentCopy(); return `<nav class="public-nav" aria-label="Public navigation"><a class="public-brand" href="/"><img src="/assets/assets/total-solutions-logo.svg" alt="Total Solutions Cancún" width="178" height="54"></a><button class="public-menu" type="button" aria-expanded="false" aria-controls="blogPublicLinks" aria-label="${esc(c.menu)}">☰</button><div class="public-links" id="blogPublicLinks"><a href="/quienes-somos">${esc(c.navAbout)}</a><a href="/como-funciona">${esc(c.navHow)}</a><a href="/blog" aria-current="page">Blog</a><a href="/preguntas-frecuentes">${esc(c.navFaq)}</a><a class="public-cta" href="/solicitar-servico">${esc(c.navRequest)}</a><div class="public-language" aria-label="Language">${languages.map(item => `<button type="button" data-lang="${item}" aria-pressed="${lang === item}">${item === "pt-BR" ? "PT" : item.toUpperCase()}</button>`).join("")}</div></div></nav>`; };
  const footer = () => { const c = currentCopy(); return `<footer class="public-footer"><span>${esc(c.footer)}</span><span><a href="https://wa.me/529984078199" target="_blank" rel="noopener">${esc(c.whatsapp)}</a> · <a href="https://instagram.com/totalsolutionscancun" target="_blank" rel="noopener">Instagram</a></span></footer>`; };
  const setMeta = (selector, content) => document.querySelector(selector)?.setAttribute("content", content);
  const setSchema = data => { document.querySelector("script[data-blog-schema]")?.remove(); const script = document.createElement("script"); script.type = "application/ld+json"; script.dataset.blogSchema = "true"; script.textContent = JSON.stringify(data); document.head.appendChild(script); };
  const localizedArticle = index => { const c = currentCopy(); return { ...meta[index], ...c.articles[index], categoryLabel: c.categories[meta[index].category], image_alt: c.labels[meta[index].category], author: "Total Solutions Cancún" }; };
  const card = article => { const c = currentCopy(); return `<article class="blog-card"><img class="blog-card-image-editorial" src="${article.hero_image}" alt="${esc(article.image_alt)}" width="${article.width}" height="${article.height}" loading="lazy"><div class="blog-card-body"><p class="blog-category">${esc(article.categoryLabel)}</p><h3>${esc(article.title)}</h3><p>${esc(article.description)}</p><p class="blog-meta">${esc(article.author)} · ${article.minutes} ${esc(c.readTime)} · ${article.date}</p><a class="blog-link" href="${articleUrl(article)}">${esc(c.read)} <span aria-hidden="true">→</span></a></div></article>`; };
  const shell = (title, text, content) => `${nav()}<header class="blog-hero"><div class="blog-hero-inner"><p class="public-kicker">Total Solutions Cancún</p><h1>${esc(title)}</h1><p>${esc(text)}</p></div></header><main class="blog-content">${content}</main>${footer()}`;
  let globalEventsBound = false;
  const setLanguage = value => { lang = normalizeLanguage(value); localStorage.setItem(languageKey, lang); updateDocumentLanguage(); render(); };
  const bindNav = () => { const menu = document.querySelector(".public-menu"); const links = document.getElementById("blogPublicLinks"); if (menu && links) menu.addEventListener("click", () => { const open = links.classList.toggle("is-open"); menu.setAttribute("aria-expanded", String(open)); menu.textContent = open ? "×" : "☰"; menu.setAttribute("aria-label", open ? currentCopy().close : currentCopy().menu); }); if (!globalEventsBound) { document.addEventListener("click", event => { const button = event.target.closest("[data-lang]"); if (button) setLanguage(button.dataset.lang); }); globalEventsBound = true; } };
  const updateDocumentLanguage = () => { document.documentElement.lang = lang === "pt-BR" ? "pt-BR" : `${lang}-MX`; };
  const renderIndex = () => { const c = currentCopy(); const articles = meta.map((_, index) => localizedArticle(index)); const title = "Blog"; const description = lang === "en" ? "Practical ideas about professional maintenance for properties, hotels, Airbnb and investments in Cancún." : lang === "pt-BR" ? "Ideias práticas sobre manutenção profissional para imóveis, hotéis, Airbnb e investimentos em Cancún." : "Ideas prácticas sobre mantenimiento profesional para propiedades, hoteles, Airbnb e inversiones en Cancún."; document.title = `${title} | Total Solutions Cancún`; setMeta('meta[name="description"]', description); setSchema({ "@context": "https://schema.org", "@type": "CollectionPage", name: title, description, url: "https://totalsolutionscancun.com/blog", inLanguage: lang, mainEntity: articles.map(article => ({ "@type": "Article", headline: article.title, url: `https://totalsolutionscancun.com${articleUrl(article)}`, image: [`https://totalsolutionscancun.com${article.hero_image}`], author: { "@type": "Organization", name: article.author }, datePublished: article.date })) }); const filters = ["all", ...new Set(meta.map(article => article.category))]; document.body.innerHTML = shell(title, c.intro, `<div class="blog-toolbar"><div><h2>${esc(c.context)}</h2></div><p>${esc(c.toolbar)}</p></div><div class="blog-filters" role="group" aria-label="${esc(c.context)}">${filters.map((filter, index) => `<button type="button" class="blog-filter" data-filter="${filter}" aria-pressed="${index === 0}">${esc(filter === "all" ? c.all : c.categories[filter])}</button>`).join("")}</div><div class="blog-grid">${articles.map(card).join("")}</div>`); bindNav(); document.querySelectorAll(".blog-filter").forEach(button => button.addEventListener("click", () => { const filter = button.dataset.filter; document.querySelectorAll(".blog-filter").forEach(item => item.setAttribute("aria-pressed", String(item === button))); document.querySelectorAll(".blog-card").forEach((item, index) => { item.hidden = filter !== "all" && meta[index].category !== filter; }); })); };
  const renderPost = index => { const c = currentCopy(); const article = localizedArticle(index); const url = `https://totalsolutionscancun.com${articleUrl(article)}`; document.title = `${article.title} | Total Solutions Cancún`; updateDocumentLanguage(); setMeta('meta[name="description"]', article.description); document.querySelector('link[rel="canonical"]').href = url; setMeta('meta[property="og:title"]', article.title); setMeta('meta[property="og:description"]', article.description); setMeta('meta[property="og:url"]', url); setMeta('meta[property="og:image"]', `https://totalsolutionscancun.com${article.hero_image}`); setSchema({ "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, image: [`https://totalsolutionscancun.com${article.hero_image}`], inLanguage: lang, author: { "@type": "Organization", name: article.author }, publisher: { "@type": "Organization", name: "Total Solutions Cancún", logo: { "@type": "ImageObject", url: "https://totalsolutionscancun.com/assets/assets/total-solutions-logo.svg" } }, datePublished: article.date, dateModified: article.date, mainEntityOfPage: { "@type": "WebPage", "@id": url } }); const body = `<a class="blog-back" href="/blog">${esc(c.back)}</a><article class="blog-article"><p class="blog-category">${esc(article.categoryLabel)}</p><h1>${esc(article.title)}</h1><p class="blog-dek">${esc(article.description)}</p><p class="blog-meta">${esc(article.author)} · ${article.minutes} ${esc(c.readTime)} · ${article.date}</p><figure><img class="blog-card-image-editorial" src="${article.hero_image}" alt="${esc(article.image_alt)}" width="${article.width}" height="${article.height}" loading="eager"><figcaption>Total Solutions Cancún · ${esc(c.footer)}</figcaption></figure>${article.sections.map(([heading, text]) => `<section><h2>${esc(heading)}</h2><p>${esc(text)}</p></section>`).join("")}<div class="public-callout"><div><h2>${esc(c.request)}</h2><p>${esc(c.requestText)}</p></div><a href="/solicitar-servico">${esc(c.navRequest)}</a></div></article><section class="blog-related"><h2>${esc(c.related)}</h2><div class="blog-grid">${meta.map((_, relatedIndex) => relatedIndex).filter(relatedIndex => relatedIndex !== index).map(relatedIndex => card(localizedArticle(relatedIndex))).join("")}</div></section>`; document.body.innerHTML = shell(article.title, article.description, body); bindNav(); };
  const renderNotFound = () => { const c = currentCopy(); document.title = `${c.notFound} | Total Solutions Cancún`; updateDocumentLanguage(); document.body.innerHTML = shell(c.notFound, c.notFoundText, `<p>${esc(c.notFoundHelp)} <a class="blog-link" href="/blog">Blog</a>.</p>`); bindNav(); };
  const slug = decodeURIComponent(location.pathname.replace(/^\/blog\/?/, "").replace(/\/$/, ""));
  const index = meta.findIndex(article => article.slug === slug);
  updateDocumentLanguage();
  if (document.body.dataset.blogPage === "post" && index >= 0) renderPost(index); else if (document.body.dataset.blogPage === "post") renderNotFound(); else renderIndex();
})();
