(() => {
  const translations = {
    es: {
      navAbout: "Quiénes somos", navHow: "Cómo funciona", navFaq: "Preguntas frecuentes", navRequest: "Solicitar servicio", menu: "Abrir menú", close: "Cerrar menú", footer: "Mantenimiento profesional y seguimiento operativo en Cancún.", cta: "Solicitar servicio", whatsapp: "WhatsApp", instagram: "Instagram",
      about: { kicker: "Total Solutions Cancún", title: "Todo el mantenimiento, una sola solución.", intro: "Coordinamos visitas, diagnósticos, servicios, evidencias y seguimiento para que cada atención tenga orden, claridad y respaldo.", who: "Quiénes somos", whoText: "Total Solutions conecta clientes, supervisores, técnicos y organizaciones en una operación profesional de mantenimiento. Cada solicitud conserva contexto, evidencias y seguimiento desde el primer contacto.", problem: "El problema que resolvemos", problemText: "Cuando una propiedad necesita atención, coordinar personas, tiempos, diagnóstico y evidencias no debería depender de conversaciones dispersas. Organizamos ese proceso en un solo lugar.", way: "Una forma de trabajar clara", vision: "Nuestra visión", visionText: "Construir una red confiable de mantenimiento profesional en Cancún y Riviera Maya, con más trazabilidad para clientes y mejores herramientas para quienes ejecutan el servicio.", audience: "A quién atendemos", audienceItems: ["Propietarios", "Brokers", "Inmobiliarias", "Airbnb", "Hoteles", "Negocios", "Organizaciones", "Técnicos"] },
      how: { kicker: "Operación transparente", title: "¿Cómo funciona Total Solutions?", intro: "Un flujo coordinado para transformar una necesidad de mantenimiento en una atención documentada.", stages: ["Solicitud", "Diagnóstico", "Supervisor", "Técnico", "Seguimiento", "Evidencias", "Conclusión", "Garantía cuando corresponda"], actors: "Personas y equipos coordinados", actorItems: [["CLIENTE", "Solicita y acompaña"], ["SUPERVISOR", "Coordina y supervisa"], ["TÉCNICO", "Ejecuta y registra evidencias"], ["ORGANIZACIÓN", "Gestiona su operación, equipo y clientes"], ["ADMIN / ROOT", "Mantiene gobernanza, permisos y supervisión de plataforma"]] },
      faq: { kicker: "Respuestas claras", title: "Preguntas frecuentes", intro: "Información sencilla sobre cómo solicitar y acompañar un servicio.", items: [["¿Qué servicios ofrece Total Solutions?", "Coordinamos visitas, diagnósticos, mantenimiento, reparaciones, instalaciones y seguimiento documentado, según la disponibilidad y el alcance de cada solicitud."], ["¿Trabajan con hoteles, Airbnb y propiedades en renta?", "Sí. Atendemos propiedades residenciales, rentas vacacionales, hoteles, comercios, oficinas y organizaciones."], ["¿Cómo solicito una visita?", "Puedes iniciar una solicitud desde el botón Solicitar servicio y compartir la ubicación, el tipo de inmueble, el servicio y una descripción del problema."], ["¿La visita tiene un costo?", "El costo de la visita depende de la matriz vigente para el servicio y el área. La referencia se presenta durante el proceso correspondiente."], ["¿Cómo sé el estado de mi solicitud?", "Cada solicitud puede contar con un código de seguimiento público para consultar su estado operativo."], ["¿Puedo ver la ubicación del técnico?", "Cuando el seguimiento está activo y existen datos disponibles, el portal puede mostrar la última ubicación y la información de ruta correspondiente."], ["¿Cómo se asigna un técnico?", "La operación valida disponibilidad, habilidades y reglas de organización antes de realizar una asignación."], ["¿Qué pasa después del diagnóstico?", "El diagnóstico ayuda a definir el alcance recomendado y, cuando corresponde, el presupuesto para aprobación."], ["¿Existe garantía?", "Cuando aplica, la atención puede conservar evidencias y un flujo de garantía conforme a las condiciones del servicio."], ["¿Cómo contacto a Total Solutions?", "Puedes iniciar una solicitud, escribir por WhatsApp al +52 998 407 8199 o visitar @totalsolutionscancun en Instagram."]] }
    },
    en: {
      navAbout: "About us", navHow: "How it works", navFaq: "FAQ", navRequest: "Request service", menu: "Open menu", close: "Close menu", footer: "Professional maintenance and operational tracking in Cancún.", cta: "Request service", whatsapp: "WhatsApp", instagram: "Instagram",
      about: { kicker: "Total Solutions Cancún", title: "Every maintenance need, one solution.", intro: "We coordinate visits, diagnostics, services, evidence and follow-up so every service is organized, clear and accountable.", who: "Who we are", whoText: "Total Solutions connects clients, supervisors, technicians and organizations through a professional maintenance operation. Each request keeps its context, evidence and follow-up from the first contact.", problem: "The problem we solve", problemText: "When a property needs attention, coordinating people, timing, diagnosis and evidence should not depend on scattered conversations. We organize that process in one place.", way: "A clear way to work", vision: "Our vision", visionText: "To build a trusted professional maintenance network in Cancún and Riviera Maya, with better traceability for clients and better tools for service professionals.", audience: "Who we serve", audienceItems: ["Property owners", "Brokers", "Real estate companies", "Airbnb", "Hotels", "Businesses", "Organizations", "Technicians"] },
      how: { kicker: "Transparent operations", title: "How does Total Solutions work?", intro: "A coordinated flow that turns a maintenance need into a documented service.", stages: ["Request", "Diagnosis", "Supervisor", "Technician", "Follow-up", "Evidence", "Conclusion", "Warranty when applicable"], actors: "People and teams working together", actorItems: [["CLIENT", "Requests and follows along"], ["SUPERVISOR", "Coordinates and supervises"], ["TECHNICIAN", "Executes and records evidence"], ["ORGANIZATION", "Manages operations, team and clients"], ["ADMIN / ROOT", "Maintains governance, permissions and platform oversight"]] },
      faq: { kicker: "Clear answers", title: "Frequently asked questions", intro: "Straightforward information about requesting and following a service.", items: [["What services does Total Solutions offer?", "We coordinate visits, diagnostics, maintenance, repairs, installations and documented follow-up, according to each request's scope and availability."], ["Do you work with hotels, Airbnb and rental properties?", "Yes. We serve residential properties, vacation rentals, hotels, businesses, offices and organizations."], ["How do I request a visit?", "Start a request from the Request service button and share the property, service type, location and a description of the issue."], ["Does the visit have a cost?", "The visit cost depends on the current matrix for the service and area. The applicable reference is presented during the relevant process."], ["How can I check my request?", "A request may include a public tracking code for checking its operational status."], ["Can I see the technician's location?", "When tracking is active and data is available, the portal may show the latest location and route information."], ["How is a technician assigned?", "Operations validate availability, skills and organization rules before assigning a technician."], ["What happens after diagnosis?", "The diagnosis helps define the recommended scope and, when applicable, the quote for approval."], ["Is there a warranty?", "When applicable, the service can retain evidence and follow a warranty process according to its conditions."], ["How do I contact Total Solutions?", "Start a request, message WhatsApp at +52 998 407 8199 or visit @totalsolutionscancun on Instagram."]] }
    },
    "pt-BR": {
      navAbout: "Quem somos", navHow: "Como funciona", navFaq: "Perguntas frequentes", navRequest: "Solicitar serviço", menu: "Abrir menu", close: "Fechar menu", footer: "Manutenção profissional e acompanhamento operacional em Cancún.", cta: "Solicitar serviço", whatsapp: "WhatsApp", instagram: "Instagram",
      about: { kicker: "Total Solutions Cancún", title: "Toda manutenção, uma única solução.", intro: "Coordenamos visitas, diagnósticos, serviços, evidências e acompanhamento para que cada atendimento tenha ordem, clareza e respaldo.", who: "Quem somos", whoText: "A Total Solutions conecta clientes, supervisores, técnicos e organizações em uma operação profissional de manutenção. Cada solicitação mantém contexto, evidências e acompanhamento desde o primeiro contato.", problem: "O problema que resolvemos", problemText: "Quando um imóvel precisa de atendimento, coordenar pessoas, prazos, diagnóstico e evidências não deveria depender de conversas dispersas. Organizamos esse processo em um só lugar.", way: "Uma forma clara de trabalhar", vision: "Nossa visão", visionText: "Construir uma rede confiável de manutenção profissional em Cancún e Riviera Maya, com mais rastreabilidade para clientes e melhores ferramentas para quem executa o serviço.", audience: "Quem atendemos", audienceItems: ["Proprietários", "Brokers", "Imobiliárias", "Airbnb", "Hotéis", "Negócios", "Organizações", "Técnicos"] },
      how: { kicker: "Operação transparente", title: "Como funciona a Total Solutions?", intro: "Um fluxo coordenado para transformar uma necessidade de manutenção em um atendimento documentado.", stages: ["Solicitação", "Diagnóstico", "Supervisor", "Técnico", "Acompanhamento", "Evidências", "Conclusão", "Garantia quando aplicável"], actors: "Pessoas e equipes coordenadas", actorItems: [["CLIENTE", "Solicita e acompanha"], ["SUPERVISOR", "Coordena e supervisiona"], ["TÉCNICO", "Executa e registra evidências"], ["ORGANIZAÇÃO", "Gerencia sua operação, equipe e clientes"], ["ADMIN / ROOT", "Mantém governança, permissões e supervisão da plataforma"]] },
      faq: { kicker: "Respostas claras", title: "Perguntas frequentes", intro: "Informações simples sobre como solicitar e acompanhar um atendimento.", items: [["Quais serviços a Total Solutions oferece?", "Coordenamos visitas, diagnósticos, manutenção, reparos, instalações e acompanhamento documentado, conforme o escopo e a disponibilidade de cada solicitação."], ["Vocês trabalham com hotéis, Airbnb e imóveis para aluguel?", "Sim. Atendemos imóveis residenciais, locações por temporada, hotéis, comércios, escritórios e organizações."], ["Como solicito uma visita?", "Inicie uma solicitação pelo botão Solicitar serviço e informe o imóvel, o serviço, a localização e uma descrição do problema."], ["A visita tem custo?", "O custo da visita depende da matriz vigente para o serviço e a área. A referência aplicável é apresentada no processo correspondente."], ["Como acompanho minha solicitação?", "A solicitação pode ter um código público de acompanhamento para consultar seu status operacional."], ["Posso ver a localização do técnico?", "Quando o acompanhamento está ativo e há dados disponíveis, o portal pode mostrar a última localização e as informações de rota."], ["Como um técnico é atribuído?", "A operação valida disponibilidade, habilidades e regras da organização antes de atribuir um técnico."], ["O que acontece depois do diagnóstico?", "O diagnóstico ajuda a definir o escopo recomendado e, quando aplicável, o orçamento para aprovação."], ["Existe garantia?", "Quando aplicável, o atendimento pode manter evidências e seguir um fluxo de garantia conforme suas condições."], ["Como entro em contato com a Total Solutions?", "Inicie uma solicitação, escreva no WhatsApp +52 998 407 8199 ou visite @totalsolutionscancun no Instagram."]] }
    }
  };
  const langKey = value => String(value || "").toLowerCase().startsWith("pt") ? "pt-BR" : String(value || "").toLowerCase().startsWith("en") ? "en" : "es";
  let lang = langKey(new URLSearchParams(location.search).get("lang") || localStorage.getItem("totalsolutions_public_language") || navigator.language);
  const page = document.body.dataset.page;
  const copy = () => translations[lang];
  const esc = value => String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
  const nav = () => `<nav class="public-nav" aria-label="Public navigation"><a class="public-brand" href="/"><img src="/assets/assets/total-solutions-logo.svg" alt="Total Solutions Cancún"></a><button class="public-menu" type="button" aria-expanded="false" aria-controls="publicLinks" aria-label="${esc(copy().menu)}">☰</button><div class="public-links" id="publicLinks"><a href="/quienes-somos">${esc(copy().navAbout)}</a><a href="/como-funciona">${esc(copy().navHow)}</a><a href="/preguntas-frecuentes">${esc(copy().navFaq)}</a><a class="public-cta" href="/solicitar-servico">${esc(copy().navRequest)}</a><div class="public-language" aria-label="Language"><button data-lang="es" type="button" aria-pressed="${lang === "es"}">ES</button><button data-lang="en" type="button" aria-pressed="${lang === "en"}">EN</button><button data-lang="pt-BR" type="button" aria-pressed="${lang === "pt-BR"}">PT</button></div></div></nav>`;
  const footer = () => `<footer class="public-footer"><span>${esc(copy().footer)}</span><span><a href="https://wa.me/529984078199" target="_blank" rel="noopener">${esc(copy().whatsapp)}</a> · <a href="https://instagram.com/totalsolutionscancun" target="_blank" rel="noopener">${esc(copy().instagram)}</a></span></footer>`;
  const cta = () => `<div class="public-callout"><div><h2>${esc(copy().cta)}</h2><p>${esc(copy().about?.intro || copy().how?.intro || copy().faq?.intro)}</p></div><a href="/solicitar-servico">${esc(copy().cta)}</a></div>`;
  const journeyContent = () => {
    const pt = lang === "pt-BR"; const en = lang === "en";
    const words = pt ? {mapTitle: "Como a operação se conecta", mapIntro: "Uma visão única para clientes, equipes e governança.", implemented: "Implementado", partial: "Parcial", future: "Futuro", steps: "Etapas do fluxo", reuse: "Conteúdo reutilizável", video: "Material de vídeo sugerido", campaign: "Versões para campanha", duration: "Duração sugerida", script: "Roteiro curto", scenes: "Cenas / telas", email: "E-mail", whatsapp: "WhatsApp", instagram: "Instagram", landing: "Landing page", cta: "Solicitar serviço", note: "Material editorial sugerido; não representa uma funcionalidade de vídeo já publicada.", governance: "Organização e Admin / ROOT garantem governança e isolamento por organização.", nodes: ["Cliente", "Solicitação", "Supervisor", "Técnico", "Serviço", "Evidências", "Conclusão", "Garantia"]} : en ? {mapTitle: "How the operation connects", mapIntro: "One view for clients, teams and governance.", implemented: "Implemented", partial: "Partial", future: "Future", steps: "Flow stages", reuse: "Reusable content", video: "Suggested video material", campaign: "Campaign versions", duration: "Suggested duration", script: "Short script", scenes: "Scenes / screens", email: "Email", whatsapp: "WhatsApp", instagram: "Instagram", landing: "Landing page", cta: "Request service", note: "Suggested editorial material; it does not represent a published video feature.", governance: "Organization and Admin / ROOT provide governance and organization isolation.", nodes: ["Client", "Request", "Supervisor", "Technician", "Service", "Evidence", "Conclusion", "Warranty"]} : {mapTitle: "Cómo se conecta la operación", mapIntro: "Una visión única para clientes, equipos y gobernanza.", implemented: "Implementado", partial: "Parcial", future: "Futuro", steps: "Etapas del flujo", reuse: "Contenido reutilizable", video: "Material de video sugerido", campaign: "Versiones para campaña", duration: "Duración sugerida", script: "Guion corto", scenes: "Escenas / pantallas", email: "E-mail", whatsapp: "WhatsApp", instagram: "Instagram", landing: "Landing page", cta: "Solicitar servicio", note: "Material editorial sugerido; no representa una función de video ya publicada.", governance: "Organización y Admin / ROOT garantizan gobernanza y aislamiento por organización.", nodes: ["Cliente", "Solicitud", "Supervisor", "Técnico", "Servicio", "Evidencias", "Conclusión", "Garantía"]};
    const data = pt ? [
      ["cliente", "CLIENTE", "Parcial", "Da necessidade ao acompanhamento documentado.", ["Descobre a Total Solutions", "Envia solicitação, localização e evidências", "Acompanha diagnóstico, rota e conclusão", "Avalia o atendimento e consulta garantia quando aplicável"]],
      ["tecnico", "TÉCNICO", "Parcial", "Do cadastro à execução com evidências profissionais.", ["Mantém perfil e especialidades", "Recebe atribuição conforme regras da organização", "Compartilha deslocamento e registra diagnóstico", "Executa, documenta e conclui o serviço"]],
      ["supervisor", "SUPERVISOR", "Implementado", "É o elo operacional entre solicitação, técnico e conclusão.", ["Recebe e analisa a OS", "Valida localização, habilidade e disponibilidade", "Atribui e acompanha o deslocamento", "Revisa diagnóstico, evidências e conclusão"]],
      ["organizacion", "ORGANIZAÇÃO", "Parcial", "Conecta pessoas, clientes e operação com escopo próprio.", ["Organiza usuários, equipes e clientes", "Recebe leads e solicitações", "Coordena supervisores e técnicos", "Consulta campanhas, indicações e indicadores"]],
      ["admin", "ADMIN / ROOT", "Parcial", "Mantém governança, permissões e visão operacional.", ["Administra organizações e usuários", "Controla permissões e configurações", "Supervisiona operações e auditoria", "Evolui qualidade, campanhas e governança"]]
    ] : en ? [
      ["cliente", "CLIENT", "Partial", "From the need to documented follow-up.", ["Discovers Total Solutions", "Sends request, location and evidence", "Follows diagnosis, route and conclusion", "Reviews the service and warranty when applicable"]],
      ["tecnico", "TECHNICIAN", "Partial", "From profile to execution with professional evidence.", ["Maintains profile and skills", "Receives assignment under organization rules", "Shares travel status and records diagnosis", "Executes, documents and closes the service"]],
      ["supervisor", "SUPERVISOR", "Implemented", "The operational link between the request, technician and conclusion.", ["Receives and reviews the order", "Validates location, skill and availability", "Assigns and follows the route", "Reviews diagnosis, evidence and conclusion"]],
      ["organizacion", "ORGANIZATION", "Partial", "Connects people, clients and operations within its scope.", ["Organizes users, teams and clients", "Receives leads and requests", "Coordinates supervisors and technicians", "Reviews campaigns, referrals and indicators"]],
      ["admin", "ADMIN / ROOT", "Partial", "Maintains governance, permissions and operational visibility.", ["Manages organizations and users", "Controls permissions and settings", "Oversees operations and audit", "Evolves quality, campaigns and governance"]]
    ] : [
      ["cliente", "CLIENTE", "Parcial", "De la necesidad al seguimiento documentado.", ["Descubre Total Solutions", "Envía solicitud, ubicación y evidencias", "Acompaña diagnóstico, ruta y conclusión", "Evalúa el servicio y consulta garantía cuando aplica"]],
      ["tecnico", "TÉCNICO", "Parcial", "Del perfil a la ejecución con evidencia profesional.", ["Mantiene perfil y especialidades", "Recibe asignación según reglas de la organización", "Comparte desplazamiento y registra diagnóstico", "Ejecuta, documenta y cierra el servicio"]],
      ["supervisor", "SUPERVISOR", "Implementado", "Es el enlace operativo entre la solicitud, el técnico y la conclusión.", ["Recibe y analiza la OS", "Valida ubicación, habilidad y disponibilidad", "Asigna y acompaña la ruta", "Revisa diagnóstico, evidencias y conclusión"]],
      ["organizacion", "ORGANIZACIÓN", "Parcial", "Conecta personas, clientes y operación dentro de su alcance.", ["Organiza usuarios, equipos y clientes", "Recibe leads y solicitudes", "Coordina supervisores y técnicos", "Consulta campañas, referidos e indicadores"]],
      ["admin", "ADMIN / ROOT", "Parcial", "Mantiene gobernanza, permisos y visión operativa.", ["Administra organizaciones y usuarios", "Controla permisos y configuraciones", "Supervisa operación y auditoría", "Evoluciona calidad, campañas y gobernanza"]]
    ];
    return {words, data};
  };
  const journeyMarkup = () => { const {words, data} = journeyContent(); const status = value => value === words.implemented ? "implemented" : value === words.future ? "future" : "partial"; return `<section class="public-section journey-overview"><h2>${esc(words.mapTitle)}</h2><p>${esc(words.mapIntro)}</p><nav class="journey-nav" aria-label="${esc(words.mapTitle)}">${data.map(([id, role]) => `<a href="#${id}">${esc(role)}</a>`).join("")}</nav><div class="journey-map" role="img" aria-label="${esc(words.mapTitle)}"><div class="journey-map-core">Total Solutions</div><div class="journey-map-nodes">${words.nodes.map((node, i) => `<span class="journey-map-node node-${i}">${esc(node)}</span>`).join("")}</div><p class="journey-map-governance">${esc(words.governance)}</p></div></section>${data.map(([id, role, state, intro, steps]) => `<section id="${id}" class="public-section journey-section"><div class="journey-heading"><div><p class="public-kicker">${esc(role)}</p><h2>${esc(role)}</h2></div><span class="journey-badge ${status(state)}">${esc(state)}</span></div><p>${esc(intro)}</p><h3>${esc(words.steps)}</h3><ol class="journey-step-list">${steps.map(step => `<li class="journey-step"><span></span><strong>${esc(step)}</strong></li>`).join("")}</ol><div class="journey-reuse"><article class="journey-reuse-card"><h3>${esc(words.video)}</h3><p><strong>${esc(role)}: ${esc(words.mapTitle)}</strong></p><p>${esc(words.duration)}: 60–90 s</p><p>${esc(words.script)}: ${esc(intro)}</p><p>${esc(words.scenes)}: ${esc(steps.slice(0, 3).join(" · "))}</p></article><article class="journey-reuse-card"><h3>${esc(words.campaign)}</h3><p><strong>${esc(words.email)}:</strong> ${esc(intro)}</p><p><strong>${esc(words.whatsapp)}:</strong> ${esc(steps[0])} → ${esc(words.cta)}</p><p><strong>${esc(words.instagram)}:</strong> ${esc(role)} · ${esc(words.cta)}</p><p><strong>${esc(words.landing)}:</strong> ${esc(intro)}</p></article></div><p class="journey-note">${esc(words.note)}</p></section>`).join("")}`; };
  const render = () => {
    const c = copy(); let main = ""; let metaTitle = "";
    if (page === "about") { metaTitle = c.about.title; main = `<section class="public-section"><h2>${esc(c.about.who)}</h2><p>${esc(c.about.whoText)}</p></section><section class="public-section"><h2>${esc(c.about.problem)}</h2><p>${esc(c.about.problemText)}</p></section><section class="public-section"><h2>${esc(c.about.way)}</h2><div class="public-grid">${["Solicitud", "Diagnóstico", "Supervisor", "Técnico", "Seguimiento", "Evidencias", "Conclusión", "Garantía"].map((item, i) => `<article class="public-card"><h3>${String(i + 1).padStart(2, "0")} · ${esc(c.how.stages[i])}</h3><p>${esc(c.how.stages[i])}</p></article>`).join("")}</div></section><section class="public-section"><h2>${esc(c.about.audience)}</h2><ul class="public-list">${c.about.audienceItems.map(item => `<li>${esc(item)}</li>`).join("")}</ul></section><section class="public-section"><h2>${esc(c.about.vision)}</h2><p>${esc(c.about.visionText)}</p></section>`; }
    if (page === "how") { metaTitle = c.how.title; main = `<section class="public-section"><h2>${esc(c.how.title)}</h2><p>${esc(c.how.intro)}</p><div class="public-steps">${c.how.stages.map(stage => `<div class="public-step"><div><h3>${esc(stage)}</h3><p>${esc(stage)}</p></div></div>`).join("")}</div></section>${journeyMarkup()}`; }
    if (page === "faq") { metaTitle = c.faq.title; main = `<section class="public-section"><h2>${esc(c.faq.title)}</h2><p>${esc(c.faq.intro)}</p><div>${c.faq.items.map(([q, a]) => `<details class="public-faq"><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join("")}</div></section>`; }
    document.title = `${metaTitle} | Total Solutions Cancún`;
    document.documentElement.lang = lang === "pt-BR" ? "pt-BR" : `${lang}-MX`;
    document.body.innerHTML = `${nav()}<header class="public-hero"><div class="public-hero-inner"><p class="public-kicker">${esc(page === "about" ? c.about.kicker : page === "how" ? c.how.kicker : c.faq.kicker)}</p><h1>${esc(metaTitle)}</h1><p>${esc(page === "about" ? c.about.intro : page === "how" ? c.how.intro : c.faq.intro)}</p></div></header><main class="public-main">${main}${cta()}</main>${footer()}`;
    document.querySelectorAll("[data-lang]").forEach(button => button.addEventListener("click", () => { lang = button.dataset.lang; localStorage.setItem("totalsolutions_public_language", lang); render(); }));
    const menu = document.querySelector(".public-menu"); const links = document.getElementById("publicLinks");
    menu.addEventListener("click", () => { const open = links.classList.toggle("is-open"); menu.setAttribute("aria-expanded", String(open)); menu.textContent = open ? "×" : "☰"; menu.setAttribute("aria-label", open ? copy().close : copy().menu); });
  };
  render();
})();
