-- NETWORK-01: additive membership/transfer foundation.
-- This migration does not alter users.organization_id or any historical record.

CREATE TABLE IF NOT EXISTS network_fee_policies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER REFERENCES organizations(id),
    network_id INTEGER,
    country VARCHAR(8) NOT NULL,
    region VARCHAR(120),
    service_origin VARCHAR(32) NOT NULL DEFAULT 'NETWORK',
    platform_fee_rate VARCHAR(32),
    tax_policy VARCHAR(64),
    currency VARCHAR(8) NOT NULL DEFAULT 'MXN',
    effective_from TIMESTAMP,
    effective_until TIMESTAMP,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS organization_memberships (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    membership_type VARCHAR(32) NOT NULL DEFAULT 'TECHNICIAN',
    role VARCHAR(32) NOT NULL DEFAULT 'TECHNICIAN',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    supervisor_user_id INTEGER REFERENCES users(id),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_operational BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP,
    approved_at TIMESTAMP,
    approved_by_user_id INTEGER REFERENCES users(id),
    exited_at TIMESTAMP,
    exit_reason VARCHAR(240),
    requested_at TIMESTAMP,
    requested_by_user_id INTEGER REFERENCES users(id),
    terms_version VARCHAR(64),
    terms_accepted_at TIMESTAMP,
    terms_acceptance_ip_hash VARCHAR(128),
    terms_acceptance_metadata_json TEXT,
    fee_policy_id INTEGER REFERENCES network_fee_policies(id),
    territory_country VARCHAR(8),
    territory_state VARCHAR(80),
    territory_city VARCHAR(120),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_organization_membership_user_org UNIQUE (user_id, organization_id)
);

CREATE TABLE IF NOT EXISTS technician_transfer_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    from_organization_id INTEGER NOT NULL REFERENCES organizations(id),
    to_organization_id INTEGER NOT NULL REFERENCES organizations(id),
    status VARCHAR(40) NOT NULL DEFAULT 'TRANSFER_REQUESTED',
    requested_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    reviewed_by_user_id INTEGER REFERENCES users(id),
    reason TEXT,
    review_notes TEXT,
    terms_version VARCHAR(64),
    terms_accepted_at TIMESTAMP,
    requested_transfer_type VARCHAR(32) NOT NULL DEFAULT 'NETWORK_MEMBERSHIP',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_organization_memberships_user ON organization_memberships(user_id);
CREATE INDEX IF NOT EXISTS idx_organization_memberships_org_status ON organization_memberships(organization_id, status);
CREATE INDEX IF NOT EXISTS idx_organization_memberships_operational ON organization_memberships(user_id, is_operational, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_organization_memberships_primary_active_user
    ON organization_memberships(user_id)
    WHERE is_primary = TRUE AND status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS idx_technician_transfer_requests_user ON technician_transfer_requests(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_technician_transfer_requests_status ON technician_transfer_requests(status, created_at);
