-- Stripe reconciliation foundation. Deliberately separate from application startup.
-- No existing payment, ledger, organization or user rows are modified.

CREATE TABLE IF NOT EXISTS stripe_webhook_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL UNIQUE,
    event_type VARCHAR(96) NOT NULL,
    livemode BOOLEAN,
    object_id VARCHAR(255),
    payment_id INTEGER REFERENCES payments(id),
    organization_id INTEGER REFERENCES organizations(id),
    status VARCHAR(24) NOT NULL DEFAULT 'PROCESSING',
    attempts INTEGER NOT NULL DEFAULT 1,
    received_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    last_error VARCHAR(240)
);

CREATE TABLE IF NOT EXISTS stripe_payment_adjustments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id INTEGER NOT NULL REFERENCES payments(id),
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    stripe_event_id VARCHAR(255) NOT NULL UNIQUE,
    provider_adjustment_id VARCHAR(255) NOT NULL,
    kind VARCHAR(24) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL,
    ledger_idempotency_key VARCHAR(255) UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_stripe_payment_adjustment_provider UNIQUE (kind, provider_adjustment_id)
);

CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_status
    ON stripe_webhook_events(status, received_at);
CREATE INDEX IF NOT EXISTS idx_stripe_webhook_events_payment
    ON stripe_webhook_events(payment_id, received_at);
CREATE INDEX IF NOT EXISTS idx_stripe_payment_adjustments_payment
    ON stripe_payment_adjustments(payment_id, kind, status);
