CREATE TABLE IF NOT EXISTS identity_verifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    organization_id INTEGER REFERENCES organizations(id),
    status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
    provider VARCHAR(64),
    external_reference VARCHAR(128),
    verified_at TIMESTAMP,
    expires_at TIMESTAMP,
    next_action_code VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_identity_verification_user_org UNIQUE (user_id, organization_id),
    CONSTRAINT ck_identity_verification_status CHECK (
        status IN (
            'NOT_STARTED', 'IN_PROGRESS', 'PENDING_REVIEW', 'NEEDS_ACTION',
            'VERIFIED', 'REJECTED', 'EXPIRED', 'SUSPENDED'
        )
    )
);

CREATE INDEX IF NOT EXISTS ix_identity_verifications_user_id ON identity_verifications (user_id);
CREATE INDEX IF NOT EXISTS ix_identity_verifications_organization_id ON identity_verifications (organization_id);
CREATE INDEX IF NOT EXISTS ix_identity_verifications_status ON identity_verifications (status);
