-- IDENTITY-02B: provider attempts and deduplicated webhook audit.
-- Apply manually in a controlled migration run; startup must not execute this SQL.
CREATE TABLE IF NOT EXISTS identity_verification_attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    organization_id INTEGER REFERENCES organizations(id),
    identity_verification_id INTEGER NOT NULL REFERENCES identity_verifications(id),
    attempt_key_hash VARCHAR(64) NOT NULL UNIQUE,
    provider VARCHAR(64) NOT NULL,
    provider_mode VARCHAR(32) NOT NULL,
    policy VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    consented_at TIMESTAMP NOT NULL,
    consent_version VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    external_reference VARCHAR(128),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_identity_attempt_status CHECK (
        status IN ('CREATED', 'IN_PROGRESS', 'PENDING_REVIEW', 'REJECTED', 'EXPIRED')
    ),
    CONSTRAINT ck_identity_attempt_provider CHECK (provider IN ('metamap'))
);

CREATE TABLE IF NOT EXISTS identity_verification_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    provider_event_id VARCHAR(128) NOT NULL,
    identity_verification_attempt_id INTEGER REFERENCES identity_verification_attempts(id),
    event_name VARCHAR(64) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'RECEIVED',
    reason_code VARCHAR(64),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT uq_identity_provider_event UNIQUE (provider, provider_event_id)
);

CREATE INDEX IF NOT EXISTS ix_identity_attempts_user_id ON identity_verification_attempts (user_id);
CREATE INDEX IF NOT EXISTS ix_identity_attempts_organization_id ON identity_verification_attempts (organization_id);
CREATE INDEX IF NOT EXISTS ix_identity_attempts_identity_id ON identity_verification_attempts (identity_verification_id);
CREATE INDEX IF NOT EXISTS ix_identity_verification_attempts_status ON identity_verification_attempts (status);
CREATE INDEX IF NOT EXISTS ix_identity_events_attempt_id ON identity_verification_events (identity_verification_attempt_id);
