-- IDENTITY-03A: append-only human review decisions.
-- Apply manually in a controlled migration run; startup must not execute this SQL.

CREATE TABLE IF NOT EXISTS identity_human_review_decisions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES identity_verification_attempts(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    reviewer_user_id INTEGER NOT NULL REFERENCES users(id),
    reviewer_organization_id INTEGER NOT NULL REFERENCES organizations(id),
    decision VARCHAR(32) NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    idempotency_key_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_identity_review_decision CHECK (
        decision IN ('APPROVE', 'REJECT', 'REQUEST_CHANGES')
    ),
    CONSTRAINT ck_identity_review_reason_code CHECK (
        reason_code IN (
            'PROVIDER_RESULT_REVIEW',
            'DOCUMENT_CLARIFICATION',
            'INSUFFICIENT_EVIDENCE',
            'POLICY_CHECK'
        )
    ),
    CONSTRAINT ck_identity_review_tenant_match CHECK (
        organization_id = reviewer_organization_id
    )
);

CREATE INDEX IF NOT EXISTS ix_identity_review_decisions_attempt_id
    ON identity_human_review_decisions (attempt_id, created_at);
CREATE INDEX IF NOT EXISTS ix_identity_review_decisions_organization_id
    ON identity_human_review_decisions (organization_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_identity_review_terminal_attempt
    ON identity_human_review_decisions (attempt_id)
    WHERE decision IN ('APPROVE', 'REJECT');
