-- Provider-agnostic technician earnings foundation. Manual migration only.
-- This migration does not create payouts, transfers, wallets or balances.

CREATE TABLE IF NOT EXISTS technician_earnings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    service_order_id INTEGER NOT NULL REFERENCES service_orders(id),
    technician_user_id INTEGER NOT NULL REFERENCES users(id),
    payment_id INTEGER REFERENCES payments(id),
    currency VARCHAR(8) NOT NULL DEFAULT 'MXN',
    gross_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    platform_fee_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    processing_fee_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    net_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    policy_version VARCHAR(64) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_reference VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PROCESSING',
    reversal_of_id INTEGER REFERENCES technician_earnings(id),
    idempotency_key_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_technician_earning_status CHECK (status IN ('PROCESSING', 'IN_GUARANTEE', 'AVAILABLE_FOR_PAYMENT', 'PAYMENT_REQUESTED', 'PAID', 'HELD', 'REVERSED')),
    CONSTRAINT ck_technician_earning_nonnegative_amounts CHECK (gross_amount >= 0 AND platform_fee_amount >= 0 AND processing_fee_amount >= 0),
    CONSTRAINT ck_technician_earning_net_consistent CHECK (net_amount = gross_amount - platform_fee_amount - processing_fee_amount)
);

CREATE TABLE IF NOT EXISTS technician_earning_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    earning_id INTEGER NOT NULL REFERENCES technician_earnings(id) ON DELETE CASCADE,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    event_type VARCHAR(32) NOT NULL,
    previous_status VARCHAR(32),
    new_status VARCHAR(32) NOT NULL,
    actor_user_id INTEGER REFERENCES users(id),
    reason_code VARCHAR(64) NOT NULL,
    idempotency_key_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_technician_earning_event_type CHECK (event_type IN ('CREATED', 'STATUS_CHANGED', 'REVERSED')),
    CONSTRAINT ck_technician_earning_event_reason_code CHECK (reason_code IN ('EARNING_CREATED', 'ELIGIBILITY_CONFIRMED', 'GUARANTEE_CLOSED', 'REFUND_OR_DISPUTE', 'IDENTITY_SUSPENDED', 'ADMINISTRATIVE_HOLD', 'CORRECTION'))
);

CREATE INDEX IF NOT EXISTS idx_technician_earnings_technician_status
    ON technician_earnings(organization_id, technician_user_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_technician_earnings_order
    ON technician_earnings(organization_id, service_order_id, created_at);
CREATE INDEX IF NOT EXISTS idx_technician_earning_events_earning
    ON technician_earning_events(earning_id, created_at);
