-- Versioned technician compensation policy and immutable service-order snapshots.
-- Manual migration only. No seeds, backfill, earnings, payouts or ledger writes.

ALTER TABLE service_order_quote_items
    ADD COLUMN IF NOT EXISTS compensation_category VARCHAR(24);

CREATE TABLE IF NOT EXISTS technician_compensation_policies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    version INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    currency VARCHAR(8) NOT NULL DEFAULT 'MXN',
    technician_share_bps INTEGER NOT NULL DEFAULT 7500,
    organization_share_bps INTEGER NOT NULL DEFAULT 2500,
    default_guarantee_days INTEGER NOT NULL DEFAULT 7,
    installment_rule VARCHAR(64) NOT NULL DEFAULT 'PROPORTIONAL_CONFIRMED_INSTALLMENTS',
    processor_fee_responsibility VARCHAR(24) NOT NULL DEFAULT 'ORGANIZATION',
    discount_rule VARCHAR(32) NOT NULL DEFAULT 'ORGANIZATION_SHARE_ONLY',
    effective_from TIMESTAMP NOT NULL,
    created_by INTEGER NOT NULL REFERENCES users(id),
    activated_by INTEGER REFERENCES users(id),
    idempotency_key_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_compensation_policy_org_currency_version UNIQUE (organization_id, currency, version),
    CONSTRAINT ck_compensation_policy_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_compensation_policy_nonnegative_bps CHECK (technician_share_bps >= 0 AND organization_share_bps >= 0),
    CONSTRAINT ck_compensation_policy_bps_total CHECK (technician_share_bps + organization_share_bps = 10000),
    CONSTRAINT ck_compensation_policy_guarantee_days CHECK (default_guarantee_days >= 0)
);

CREATE TABLE IF NOT EXISTS service_order_compensation_snapshots (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    service_order_id INTEGER NOT NULL REFERENCES service_orders(id),
    technician_user_id INTEGER NOT NULL REFERENCES users(id),
    policy_id INTEGER NOT NULL REFERENCES technician_compensation_policies(id),
    policy_version INTEGER NOT NULL,
    currency VARCHAR(8) NOT NULL,
    labor_base_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    material_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    reimbursement_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    technician_share_bps INTEGER NOT NULL,
    organization_share_bps INTEGER NOT NULL,
    technician_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    organization_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    guarantee_days INTEGER NOT NULL,
    installment_rule VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PROPOSED',
    approved_by INTEGER REFERENCES users(id),
    frozen_at TIMESTAMP,
    idempotency_key_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_compensation_snapshot_status CHECK (status IN ('PROPOSED', 'FROZEN', 'VOID')),
    CONSTRAINT ck_compensation_snapshot_nonnegative_amounts CHECK (labor_base_amount >= 0 AND material_amount >= 0 AND tax_amount >= 0 AND reimbursement_amount >= 0 AND discount_amount >= 0),
    CONSTRAINT ck_compensation_snapshot_share_amounts CHECK (technician_amount >= 0 AND organization_amount >= 0)
);

CREATE TABLE IF NOT EXISTS technician_compensation_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    policy_id INTEGER REFERENCES technician_compensation_policies(id),
    snapshot_id INTEGER REFERENCES service_order_compensation_snapshots(id),
    event_type VARCHAR(32) NOT NULL,
    actor_user_id INTEGER REFERENCES users(id),
    reason_code VARCHAR(64) NOT NULL,
    idempotency_key_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_compensation_event_type CHECK (event_type IN ('POLICY_CREATED', 'POLICY_ACTIVATED', 'SNAPSHOT_PROPOSED', 'SNAPSHOT_FROZEN', 'SNAPSHOT_VOIDED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_compensation_policy_active_org_currency
    ON technician_compensation_policies(organization_id, currency)
    WHERE status = 'ACTIVE';
CREATE INDEX IF NOT EXISTS idx_compensation_snapshot_order_status
    ON service_order_compensation_snapshots(organization_id, service_order_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_compensation_snapshot_technician
    ON service_order_compensation_snapshots(organization_id, technician_user_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_compensation_events_snapshot
    ON technician_compensation_events(snapshot_id, created_at);
