-- Payment/installment reconciliation for technician earning automation.
-- Manual migration only; no backfill, payout, transfer or startup DDL.

ALTER TABLE technician_earning_events DROP CONSTRAINT IF EXISTS ck_technician_earning_event_type;
ALTER TABLE technician_earning_events ADD CONSTRAINT ck_technician_earning_event_type CHECK (
    event_type IN ('CREATED', 'STATUS_CHANGED', 'REVERSED', 'EARNING_RECOGNIZED', 'EARNING_ADJUSTED', 'EARNING_REVERSED', 'GUARANTEE_STARTED', 'AVAILABLE_FOR_PAYMENT')
);
ALTER TABLE technician_earning_events DROP CONSTRAINT IF EXISTS ck_technician_earning_event_reason_code;
ALTER TABLE technician_earning_events ADD CONSTRAINT ck_technician_earning_event_reason_code CHECK (
    reason_code IN ('EARNING_CREATED', 'ELIGIBILITY_CONFIRMED', 'GUARANTEE_CLOSED', 'REFUND_OR_DISPUTE', 'IDENTITY_SUSPENDED', 'ADMINISTRATIVE_HOLD', 'CORRECTION', 'PAYMENT_CONFIRMED', 'REFUND_OR_DISPUTE_ADJUSTMENT', 'GUARANTEE_STARTED', 'AVAILABLE_FOR_PAYMENT')
);

CREATE TABLE IF NOT EXISTS technician_earning_reconciliation_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    service_order_id INTEGER NOT NULL REFERENCES service_orders(id),
    technician_user_id INTEGER NOT NULL REFERENCES users(id),
    payment_id INTEGER NOT NULL REFERENCES payments(id),
    installment_id INTEGER REFERENCES service_order_payment_installments(id),
    earning_id INTEGER REFERENCES technician_earnings(id),
    reversal_of_earning_id INTEGER REFERENCES technician_earnings(id),
    provider_event_key_hash VARCHAR(64) NOT NULL UNIQUE,
    event_type VARCHAR(32) NOT NULL,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency VARCHAR(8) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_technician_earning_reconciliation_type CHECK (event_type IN ('PAYMENT_CONFIRMED', 'REFUND', 'DISPUTE_OPEN', 'DISPUTE_WON', 'DISPUTE_LOST')),
    CONSTRAINT ck_technician_earning_reconciliation_amount CHECK (amount >= 0)
);

CREATE INDEX IF NOT EXISTS idx_technician_earning_reconciliation_order
    ON technician_earning_reconciliation_events(organization_id, service_order_id, currency, created_at);
CREATE INDEX IF NOT EXISTS idx_technician_earning_reconciliation_payment
    ON technician_earning_reconciliation_events(payment_id, installment_id, event_type);

CREATE INDEX IF NOT EXISTS idx_technician_earnings_due_release
    ON technician_earnings(status, updated_at, service_order_id);
