BEGIN;

CREATE TABLE IF NOT EXISTS customer_service_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    customer_user_id INTEGER NOT NULL REFERENCES users(id),
    service_request_id INTEGER NOT NULL REFERENCES service_requests(id),
    verification_method VARCHAR(32) NOT NULL,
    verified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    revoked_at TIMESTAMP NULL,
    CONSTRAINT uq_customer_service_link UNIQUE (customer_user_id, service_request_id)
);

CREATE TABLE IF NOT EXISTS customer_claim_tokens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    service_request_id INTEGER NOT NULL REFERENCES service_requests(id),
    token_hash VARCHAR(64) NOT NULL,
    channel VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP NULL,
    revoked_at TIMESTAMP NULL,
    CONSTRAINT uq_customer_claim_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_customer_service_links_customer_active
    ON customer_service_links (customer_user_id, organization_id, active);
CREATE INDEX IF NOT EXISTS idx_customer_service_links_request
    ON customer_service_links (service_request_id, organization_id);
CREATE INDEX IF NOT EXISTS idx_customer_claim_tokens_request
    ON customer_claim_tokens (service_request_id, organization_id);

COMMIT;
