BEGIN;

CREATE TABLE IF NOT EXISTS customer_portal_invitations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    service_request_id INTEGER NOT NULL REFERENCES service_requests(id),
    channel VARCHAR(16) NOT NULL,
    destination_hash VARCHAR(64) NOT NULL,
    masked_destination VARCHAR(160) NOT NULL,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    language VARCHAR(12) NOT NULL DEFAULT 'es',
    status VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
    expires_at TIMESTAMP NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL UNIQUE,
    created_by_user_id INTEGER NOT NULL REFERENCES users(id),
    revoked_at TIMESTAMP NULL,
    consumed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_customer_portal_invitations_request
    ON customer_portal_invitations (service_request_id, organization_id, channel, status);
CREATE INDEX IF NOT EXISTS idx_customer_portal_invitations_destination
    ON customer_portal_invitations (destination_hash, organization_id, status);

CREATE TABLE IF NOT EXISTS customer_portal_invitation_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id INTEGER NOT NULL REFERENCES customer_portal_invitations(id),
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    event_type VARCHAR(40) NOT NULL,
    actor_user_id INTEGER NULL REFERENCES users(id),
    metadata_json TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_customer_portal_invitation_events_invitation
    ON customer_portal_invitation_events (invitation_id, created_at);

ALTER TABLE email_outbox
    ADD COLUMN IF NOT EXISTS customer_portal_invitation_id INTEGER NULL REFERENCES customer_portal_invitations(id);
CREATE INDEX IF NOT EXISTS idx_email_outbox_customer_portal_invitation
    ON email_outbox (customer_portal_invitation_id);

COMMIT;
