BEGIN;

CREATE TABLE IF NOT EXISTS external_payment_confirmations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id),
    service_order_id INTEGER NOT NULL REFERENCES service_orders(id),
    payment_id INTEGER NOT NULL REFERENCES payments(id),
    purpose VARCHAR(32) NOT NULL,
    payment_method VARCHAR(32) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    external_reference VARCHAR(120) NOT NULL,
    evidence_reference VARCHAR(240) NULL,
    observation TEXT NULL,
    confirmed_by_user_id INTEGER NOT NULL REFERENCES users(id),
    confirmed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_external_payment_confirmation_reference UNIQUE (organization_id, external_reference),
    CONSTRAINT uq_external_payment_confirmation_payment UNIQUE (payment_id),
    CONSTRAINT ck_external_payment_confirmation_amount CHECK (amount > 0),
    CONSTRAINT ck_external_payment_confirmation_currency CHECK (currency IN ('MXN', 'USD', 'CAD', 'EUR')),
    CONSTRAINT ck_external_payment_confirmation_purpose CHECK (purpose IN ('VISIT', 'SERVICE', 'INSTALLMENT'))
);

CREATE INDEX IF NOT EXISTS idx_external_payment_confirmation_order
    ON external_payment_confirmations (service_order_id, organization_id, confirmed_at);

COMMIT;
